apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "copalibre.fullname" . }}-env
  labels:
    {{- include "copalibre.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if not (has $key $.Values.secretKeys) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
