{{- if .Values.doctor.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "copalibre.fullname" . }}-doctor-{{ .Release.Revision }}
  labels:
    {{- include "copalibre.labels" . | nindent 4 }}
    app.kubernetes.io/component: doctor
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: copalibre
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: doctor
    spec:
      restartPolicy: Never
      containers:
        - name: doctor
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PRODUCT_ROLE
              value: doctor
          envFrom:
            - configMapRef:
                name: {{ include "copalibre.fullname" . }}-env
            - secretRef:
                name: {{ include "copalibre.fullname" . }}-secret
{{- end }}
