apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copalibre.fullname" . }}-secret
  labels:
    {{- include "copalibre.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{- if has $key $.Values.secretKeys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
