import {
  BREAKPOINTS,
  COLOR_PRIMITIVES,
  CONTROL_DENSITY_SPACING,
  FONT_SIZE,
  FONT_WEIGHTS,
  MOTION,
  RADIUS,
  SPACING,
  TOUCH_TARGET,
  TYPOGRAPHY,
} from '../primitives.js';
import {
  BUTTON_VARIANTS,
  CARD_STATES,
  CHECKBOX_TOKENS,
  DIALOG_TOKENS,
  FOCUS_RING,
  INPUT_TOKENS,
  SELECT_TOKENS,
  TEXTAREA_TOKENS,
  type FormControlState,
  type FormControlTokenSet,
} from '../components.js';
import { SEMANTIC_COLORS, type SemanticColor } from '../semantic.js';

/**
 * CSS custom properties and component classes.
 *
 * Emitted as a plain stylesheet with no runtime: the public surfaces are Astro
 * and Starlight, and a token system that needed JavaScript to produce a colour
 * would be a token system that fails with JavaScript disabled — on the one
 * surface most likely to be behind a hotel proxy or on a venue TV.
 */

export function generateCss(): string {
  return [
    header(),
    `:root {`,
    ...Object.entries(COLOR_PRIMITIVES).map(([name, value]) => `  --cl-color-${name}: ${value};`),
    '',
    ...Object.entries(SEMANTIC_COLORS).map(
      ([name, token]) => `  --cl-${name}: var(--cl-color-${token.primitive});`,
    ),
    '',
    `  --cl-font-display: ${TYPOGRAPHY.display};`,
    `  --cl-font-body: ${TYPOGRAPHY.body};`,
    `  --cl-font-mono: ${TYPOGRAPHY.mono};`,
    ...Object.entries(FONT_WEIGHTS).map(([name, value]) => `  --cl-weight-${name}: ${value};`),
    ...Object.entries(FONT_SIZE).map(([name, value]) => `  --cl-font-size-${name}: ${value};`),
    '',
    ...Object.entries(SPACING).map(([name, value]) => `  --cl-space-${name}: ${value};`),
    ...Object.entries(RADIUS).map(([name, value]) => `  --cl-radius-${name}: ${value};`),
    ...Object.entries(BREAKPOINTS).map(([name, value]) => `  --cl-breakpoint-${name}: ${value};`),
    '',
    ...Object.entries(MOTION).map(([name, value]) => `  --cl-motion-${name}: ${value};`),
    `  --cl-touch-target: ${TOUCH_TARGET};`,
    `}`,
    '',
    reducedMotion(),
    '',
    chamfer(),
    '',
    imageFrame(),
    '',
    components(),
    '',
    formControls(),
    '',
    dialog(),
    '',
    density(),
  ].join('\n');
}

function header(): string {
  return [
    '/* Generated by @copalibre/design-tokens. Do not edit by hand. */',
    '/* Source of truth: packages/design-tokens/src/primitives.ts */',
    '',
  ].join('\n');
}

/**
 * Under reduced motion every duration becomes zero.
 *
 * Overridden at the custom-property level rather than per component, so a
 * component added later inherits the behaviour instead of having to remember
 * it.
 */
function reducedMotion(): string {
  return [
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    `    --cl-motion-fast: ${MOTION.instant};`,
    `    --cl-motion-base: ${MOTION.instant};`,
    `    --cl-motion-slow: ${MOTION.instant};`,
    '  }',
    '',
    '  *, *::before, *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '  }',
    '}',
  ].join('\n');
}

/**
 * The chamfered corner, and the square one it falls back to.
 *
 * `corner-shape: bevel` where it exists, `clip-path` where it does not, and a
 * plain rectangle where neither does. The fallback is square rather than
 * rounded because a wrong-radius corner reads as a rendering bug, while a
 * square one reads as a deliberate, plainer surface.
 */
function chamfer(): string {
  return [
    '.cl-chamfer {',
    `  --cl-chamfer-size: ${RADIUS.chamfer};`,
    '  border-radius: 0;',
    '}',
    '',
    '@supports (clip-path: polygon(0 0)) {',
    '  .cl-chamfer {',
    '    clip-path: polygon(',
    '      var(--cl-chamfer-size) 0%, 100% 0%,',
    '      100% calc(100% - var(--cl-chamfer-size)),',
    '      calc(100% - var(--cl-chamfer-size)) 100%,',
    '      0% 100%, 0% var(--cl-chamfer-size)',
    '    );',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-chamfer {',
    '    clip-path: none;',
    '    corner-shape: bevel;',
    '    border-radius: var(--cl-chamfer-size);',
    '  }',
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-chamfer--control {',
    `  --cl-chamfer-size: ${RADIUS['chamfer-control']};`,
    '}',
  ].join('\n');
}

/**
 * A fixed 4:5 frame for a profile image (organization/club emblem, person
 * picture) or its placeholder — chamfered the same way `.cl-chamfer` already
 * is, `object-fit: cover` so a source whose stored aspect isn't exactly 4:5
 * (an image saved before this existed) still fills the frame without
 * distortion.
 */
function imageFrame(): string {
  return [
    '.cl-image-frame {',
    `  --cl-chamfer-size: ${RADIUS['image-frame']};`,
    '  aspect-ratio: 4 / 5;',
    '  max-height: 512px;',
    '  border: 1px solid var(--cl-border-muted);',
    '  border-radius: 0;',
    '  overflow: hidden;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: var(--cl-surface-raised);',
    '}',
    '',
    '.cl-image-frame img {',
    '  width: 100%;',
    '  height: 100%;',
    '  object-fit: cover;',
    '  display: block;',
    '}',
    '',
    '.cl-image-frame svg {',
    '  width: 55%;',
    '  height: 55%;',
    '}',
    '',
    '@supports (clip-path: polygon(0 0)) {',
    '  .cl-image-frame {',
    '    clip-path: polygon(',
    '      var(--cl-chamfer-size) 0%, 100% 0%,',
    '      100% calc(100% - var(--cl-chamfer-size)),',
    '      calc(100% - var(--cl-chamfer-size)) 100%,',
    '      0% 100%, 0% var(--cl-chamfer-size)',
    '    );',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-image-frame {',
    '    clip-path: none;',
    '    corner-shape: bevel;',
    '    border-radius: var(--cl-chamfer-size);',
    '  }',
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-image-frame--control {',
    `  --cl-chamfer-size: ${RADIUS['image-frame-control']};`,
    '}',
  ].join('\n');
}

function components(): string {
  const cards = CARD_STATES.map(
    (state: SemanticColor) =>
      `.cl-card--${state.replace('state-', '')} { border-left-color: var(--cl-${state}); }`,
  );

  const buttons = Object.entries(BUTTON_VARIANTS).map(([variant, tokens]) =>
    [
      `.cl-btn--${variant} {`,
      `  background: ${tokens.background === 'transparent' ? 'transparent' : `var(--cl-${tokens.background})`};`,
      `  color: var(--cl-${tokens.text});`,
      `  border-color: ${tokens.border === 'transparent' ? 'transparent' : `var(--cl-${tokens.border})`};`,
      '}',
    ].join('\n'),
  );

  return [
    '.cl-card {',
    '  background: var(--cl-surface-panel);',
    '  color: var(--cl-text-primary);',
    '  border-left: var(--cl-space-1) solid var(--cl-border-muted);',
    '  padding: var(--cl-space-4);',
    '}',
    ...cards,
    '',
    '.cl-card__header { display: grid; gap: var(--cl-space-1); margin-block-end: var(--cl-space-3); }',
    '.cl-card__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; }',
    '.cl-card__description { margin: 0; color: var(--cl-text-muted); }',
    '.cl-card__content { display: grid; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-card__footer { display: flex; gap: var(--cl-space-2); margin-block-start: var(--cl-space-4); }',
    '',
    '.cl-input, .cl-select, .cl-textarea {',
    '  min-height: var(--cl-touch-target);',
    '  font-family: var(--cl-font-body);',
    '  border: 1px solid;',
    '  padding: var(--cl-space-2) var(--cl-space-3);',
    // A bare <input>/<select>/<textarea> has a UA-stylesheet intrinsic
    // min-content width (Chromium: roughly a `size=20` input) that a narrow
    // grid track cannot override without an explicit width — without this,
    // the control forces its own grid ancestor wider than the viewport at
    // the narrowest reference width (188px, a 200%-zoom equivalent).
    '  width: 100%;',
    '  min-width: 0;',
    '  color-scheme: dark;',
    '}',
    '',
    '.cl-input::-webkit-calendar-picker-indicator {',
    '  filter: invert(0.8);',
    '  cursor: pointer;',
    '}',
    '',
    '.cl-input[type="file"] {',
    '  padding: var(--cl-space-1);',
    '}',
    '.cl-input[type="file"]::file-selector-button {',
    '  background: var(--cl-surface-raised);',
    '  color: var(--cl-text-primary);',
    '  border: 1px solid var(--cl-border-muted);',
    '  padding: var(--cl-space-1) var(--cl-space-3);',
    '  margin-right: var(--cl-space-3);',
    '  font-family: var(--cl-font-body);',
    '  font-size: var(--cl-font-size-sm);',
    '  cursor: pointer;',
    '  border-radius: var(--cl-radius-sm);',
    '  transition: background 120ms ease;',
    '}',
    '.cl-input[type="file"]::file-selector-button:hover {',
    '  background: var(--cl-surface-hover);',
    '}',
    '',
    '.cl-checkbox {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: var(--cl-touch-target);',
    '  height: var(--cl-touch-target);',
    '  border: 1px solid;',
    '}',
    'input[type="checkbox"].cl-checkbox {',
    '  appearance: none;',
    '  -webkit-appearance: none;',
    '  width: 1.25rem;',
    '  height: 1.25rem;',
    '  min-height: 1.25rem;',
    '  min-width: 1.25rem;',
    '  margin: 0;',
    '  cursor: pointer;',
    '  border-radius: var(--cl-radius-sm);',
    '  background: var(--cl-surface-base);',
    '  border: 1px solid var(--cl-border-default);',
    '  display: inline-grid;',
    '  place-content: center;',
    '  flex-shrink: 0;',
    '  color-scheme: dark;',
    '}',
    'input[type="checkbox"].cl-checkbox:hover {',
    '  border-color: var(--cl-border-hover);',
    '}',
    'input[type="checkbox"].cl-checkbox:checked {',
    '  background: var(--cl-state-live);',
    '  border-color: var(--cl-state-live);',
    '}',
    'input[type="checkbox"].cl-checkbox:checked::before {',
    '  content: "";',
    '  width: 0.55rem;',
    '  height: 0.55rem;',
    '  background-color: var(--cl-ink-950);',
    '  clip-path: polygon(14% 44%, 0 58%, 40% 98%, 100% 16%, 86% 2%, 40% 68%);',
    '}',
    'input[type="checkbox"].cl-checkbox:focus-visible {',
    '  outline: 2px solid var(--cl-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '',
    '.cl-toggle {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-2);',
    '  cursor: pointer;',
    '  user-select: none;',
    '}',
    '',
    '.cl-link {',
    '  color: var(--cl-state-live);',
    '  text-decoration: underline;',
    '  text-underline-offset: 4px;',
    '  cursor: pointer;',
    '  transition: opacity 120ms ease;',
    '}',
    '.cl-link:hover {',
    '  opacity: 0.85;',
    '}',
    '.cl-link:focus-visible {',
    '  outline: 2px solid var(--cl-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '.cl-checkbox__indicator { color: var(--cl-state-live); }',
    '.cl-select__icon { margin-inline-start: var(--cl-space-2); }',
    '.cl-select__content { padding: var(--cl-space-1); }',
    '.cl-select__item { padding: var(--cl-space-2) var(--cl-space-3); cursor: pointer; }',
    '.cl-label { font-family: var(--cl-font-mono); text-transform: uppercase; font-size: var(--cl-font-size-xs); }',
    '',
    '.cl-form-field { display: grid; gap: var(--cl-space-1); min-width: 0; }',
    '.cl-form-field__error { margin: 0; color: var(--cl-state-destructive); font-size: var(--cl-font-size-xs); }',
    '.cl-form-field__help { margin: 0; color: var(--cl-text-muted); font-size: var(--cl-font-size-xs); }',
    '.cl-decision-hint { margin: 0; color: var(--cl-text-muted); font-size: var(--cl-font-size-xs); }',
    '',
    '.cl-data-entity-card__header { display: flex; align-items: center; justify-content: space-between; }',
    '.cl-data-entity-card__metadata { display: grid; gap: var(--cl-space-2); }',
    '.cl-data-entity-card__metadata-item { display: flex; justify-content: space-between; gap: var(--cl-space-2); }',
    '.cl-data-entity-card__metadata-label { color: var(--cl-text-muted); }',
    '',
    '.cl-table-toolbar { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: var(--cl-space-3); }',
    '.cl-table-toolbar__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; }',
    '.cl-table-toolbar__filters, .cl-table-toolbar__actions { display: flex; flex-wrap: wrap; gap: var(--cl-space-2); align-items: center; }',
    '',
    '.cl-pagination { display: flex; align-items: center; gap: var(--cl-space-3); }',
    '.cl-pagination__status { color: var(--cl-text-muted); font-family: var(--cl-font-mono); }',
    '',
    '.cl-field-value { display: grid; gap: var(--cl-space-1); background: var(--cl-surface-base); padding: var(--cl-space-3); border: 1px solid var(--cl-border-muted); }',
    '.cl-field-value__label { display: block; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    '',
    '.cl-clock-ring { display: flex; align-items: center; gap: var(--cl-space-2); }',
    '',
    '.cl-data-table { padding: 0; overflow-x: auto; scrollbar-gutter: stable; }',
    '.cl-data-table__table { width: 100%; border-collapse: collapse; }',
    '.cl-data-table__table th { text-align: left; padding: var(--cl-space-3) var(--cl-space-4); border-bottom: 1px solid var(--cl-border-muted); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-data-table__table td { padding: var(--cl-space-3) var(--cl-space-4); }',
    '.cl-data-table__empty { padding: var(--cl-space-4); color: var(--cl-text-muted); }',
    '@media (max-width: 767px) { .cl-data-table { -webkit-overflow-scrolling: touch; } }',
    '',
    '.cl-modal__overlay { position: fixed; inset: 0; }',
    '.cl-modal__content { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); width: min(480px, calc(100vw - var(--cl-space-8))); max-height: 85vh; overflow-y: auto; padding: var(--cl-space-4); }',
    '.cl-modal__header { display: flex; align-items: start; justify-content: space-between; gap: var(--cl-space-3); }',
    '.cl-modal__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; }',
    '.cl-modal__description { margin: 0; color: var(--cl-text-muted); }',
    '.cl-modal__close { background: transparent; border: 0; color: var(--cl-text-primary); }',
    '.cl-modal__body { margin-block: var(--cl-space-4); display: grid; gap: var(--cl-space-3); }',
    '.cl-modal__footer { display: flex; justify-content: flex-end; gap: var(--cl-space-2); }',
    '',
    '/* Templates own inter-section spacing (design.md Decision 7) — no component below this tier sets its own external margin. */',
    '.cl-list-screen, .cl-form-screen, .cl-match-console-screen { display: grid; gap: var(--cl-density-section-gap, var(--cl-space-6)); min-width: 0; }',
    // A grid item's default `min-width: auto` sizes it to its content, which
    // silently defeats a descendant's `overflow-x: auto` (a wide table forces
    // every ancestor grid track wider instead of scrolling in place). Every
    // grid track in this template chain gets `min-width: 0` so the narrowest
    // reference width (188px, a 200%-zoom equivalent) scrolls instead of
    // overflowing the page.
    '.cl-list-screen > *, .cl-form-screen > *, .cl-match-console-screen > * { min-width: 0; }',
    '.cl-list-screen__header, .cl-form-screen__header { display: flex; align-items: end; justify-content: space-between; gap: var(--cl-space-4); flex-wrap: wrap; }',
    '.cl-list-screen__title, .cl-form-screen__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; }',
    '.cl-list-screen__breadcrumb, .cl-form-screen__breadcrumb { color: var(--cl-state-live); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-form-screen__section { display: grid; gap: var(--cl-space-3); }',
    '.cl-form-screen__section-heading { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; font-size: var(--cl-font-size-lg); }',
    '.cl-form-screen__section-fields { display: grid; gap: var(--cl-space-4); }',
    '.cl-form-screen__footer { position: sticky; bottom: 0; display: flex; justify-content: flex-end; gap: var(--cl-space-2); padding-block: var(--cl-space-3); background: var(--cl-surface-base); }',
    '.cl-list-screen__empty { margin: 0; padding: var(--cl-space-5); color: var(--cl-text-muted); }',
    '',
    '.cl-match-console-screen__header { display: flex; justify-content: space-between; align-items: start; gap: var(--cl-space-4); flex-wrap: wrap; min-width: 0; }',
    '.cl-match-console-screen__header > * { min-width: 0; }',
    '.cl-match-console-screen__title { margin: var(--cl-space-1) 0 0; font-family: var(--cl-font-display); text-transform: uppercase; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-match-console-screen__breadcrumb { color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; margin: 0; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-match-console-screen__status { display: grid; justify-items: end; color: var(--cl-state-live); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); min-width: 0; overflow-wrap: anywhere; }',
    '.cl-match-console-screen__sync-status { display: flex; flex-wrap: wrap; gap: var(--cl-space-4); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; min-width: 0; }',
    '.cl-match-console-screen__workspace { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr)); gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__workspace > * { min-width: 0; }',
    '@media (max-width: 600px) { .cl-match-console-screen__workspace { grid-template-columns: 1fr; } }',
    '.cl-match-console-screen__primary { display: grid; align-content: start; gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__rail { display: grid; align-content: start; gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__scoreboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 120px), 1fr)); border: 1px solid var(--cl-border-muted); background: var(--cl-surface-panel); min-width: 0; }',
    '.cl-match-console-screen__score-side { display: flex; justify-content: space-between; align-items: center; gap: var(--cl-space-3); padding: var(--cl-space-4); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); min-width: 0; }',
    '.cl-match-console-screen__score-entrant { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
    '.cl-match-console-screen__telemetry { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: var(--cl-space-2); min-width: 0; }',
    '.cl-match-console-screen__telemetry-item { display: grid; gap: var(--cl-space-1); border-left: 2px solid var(--cl-border-muted); padding-left: var(--cl-space-2); color: var(--cl-text-muted); min-width: 0; font-size: var(--cl-font-size-xs); }',
    '',
    '/* A row-identity chip (avatar initials + label) reused by any listing showing one person per row. */',
    '.cl-role-user { display: flex; align-items: center; gap: var(--cl-space-3); min-width: 0; flex-wrap: wrap; }',
    '.cl-role-user__avatar { display: grid; place-items: center; width: 32px; height: 32px; flex: 0 0 32px; background: var(--cl-surface-raised); border: 1px solid var(--cl-border-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    '.cl-role-user__id { display: block; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    '.cl-role-status { display: flex; align-items: center; gap: var(--cl-space-2); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-role-status--active { color: var(--cl-state-live); }',
    '.cl-role-status--inactive { color: var(--cl-text-muted); }',
    '',
    '.cl-platform-sections { display: grid; gap: var(--cl-density-section-gap, var(--cl-space-6)); min-width: 0; }',
    '.cl-platform-sections > * { min-width: 0; }',
    '.cl-platform-form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 210px), 1fr)); gap: var(--cl-space-4); align-items: end; }',
    '.cl-platform-update-list { margin: 0; padding: var(--cl-space-4); list-style-position: inside; border: 1px solid var(--cl-state-upcoming); color: var(--cl-text-secondary); }',
    '.cl-platform-modules-header { display: flex; justify-content: space-between; align-items: start; gap: var(--cl-space-4); flex-wrap: wrap; }',
    '/* A badge is a colour *and* a label; the token contract refuses one without. */',
    '.cl-badge {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-1);',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-semibold);',
    '  text-transform: uppercase;',
    '  padding: var(--cl-space-1) var(--cl-space-2);',
    '}',
    '',
    '.cl-btn {',
    '  min-height: var(--cl-touch-target);',
    '  min-width: var(--cl-touch-target);',
    '  font-family: var(--cl-font-body);',
    '  font-weight: var(--cl-weight-semibold);',
    '  border: 1px solid transparent;',
    '  padding: var(--cl-space-2) var(--cl-space-4);',
    '  transition: background var(--cl-motion-fast) var(--cl-motion-easing);',
    '}',
    ...buttons,
    '',
    '.cl-inline-alert {',
    '  display: flex;',
    '  gap: var(--cl-space-2);',
    '  padding: var(--cl-space-3);',
    '  border-left: var(--cl-space-1) solid var(--cl-state-upcoming);',
    '  background: var(--cl-surface-raised);',
    '}',
    '',
    '.cl-stat-tile {',
    '  background: var(--cl-surface-raised);',
    '  padding: var(--cl-space-4);',
    '}',
    '',
    '.cl-stat-tile__value {',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-bold);',
    '  /* Scores that shift width as they change are scores nobody can read. */',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '',
    '.cl-focusable:focus-visible {',
    '  outline: none;',
    `  box-shadow: 0 0 0 ${FOCUS_RING.innerWidth} var(--cl-surface-base),`,
    `    0 0 0 ${FOCUS_RING.outerWidth} var(--cl-focus-ring);`,
    '}',
    '',
    "/* The matches-view card (openspec 0172) — shared by MatchCard.tsx on both public-web and control-web, so it lives here rather than in either surface's own page-scoped styles. */",
    '.cl-match-card { display: grid; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-match-card__header { display: flex; align-items: center; justify-content: space-between; gap: var(--cl-space-3); }',
    '.cl-match-card__clock { font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); color: var(--cl-state-live); font-variant-numeric: tabular-nums; }',
    '.cl-match-card__sides { display: grid; gap: var(--cl-space-2); margin: 0; padding: 0; list-style: none; }',
    '.cl-match-card__side { display: flex; align-items: center; gap: var(--cl-space-2); min-width: 0; }',
    '.cl-match-card__side .cl-badge--rank { font-family: var(--cl-font-mono); font-variant-numeric: tabular-nums; flex: 0 0 auto; }',
    ".cl-match-card__side > span[data-testid='entrant-name'] { flex: 1 1 auto; font-family: var(--cl-font-display); font-weight: var(--cl-weight-medium); font-size: var(--cl-font-size-lg); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    '.cl-match-card__side .cl-stat-tile__value { flex: 0 0 auto; font-size: var(--cl-font-size-2xl); background: none; padding: 0; }',
    '.cl-match-card__scope, .cl-match-card__venue, .cl-match-card__event { margin: 0; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; letter-spacing: 0.04em; }',
    '.cl-match-card__event { color: var(--cl-text-secondary); }',
    '.cl-match-card__series { display: grid; gap: var(--cl-space-1); padding: var(--cl-space-3); background: var(--cl-surface-raised); border-left: 2px solid var(--cl-state-upcoming); }',
    '.cl-match-card__series .cl-series__score { margin: 0; font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); }',
    '.cl-match-card__series .cl-series__pending, .cl-match-card__series .cl-series__decided, .cl-match-card__series .cl-series__aggregate { margin: 0; color: var(--cl-text-secondary); font-size: var(--cl-font-size-sm); }',
    '.cl-match-card__deciding-factor { margin: 0; padding: var(--cl-space-2) var(--cl-space-3); background: var(--cl-surface-raised); border-left: 2px solid var(--cl-focus-ring); color: var(--cl-text-secondary); font-size: var(--cl-font-size-sm); }',
    '.cl-match-card__trace { border-top: 1px solid var(--cl-border-muted); padding-top: var(--cl-space-2); }',
    '.cl-match-card__trace > summary { cursor: pointer; color: var(--cl-focus-ring); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-match-card__trace-lines { margin: var(--cl-space-2) 0 0; padding-left: var(--cl-space-4); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    '.cl-matches-view__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: var(--cl-space-4); }',
  ].join('\n');
}

/** One state-keyed rule block per form-control atom. */
function formControls(): string {
  const groups: readonly [string, Record<FormControlState, FormControlTokenSet>][] = [
    ['input', INPUT_TOKENS],
    ['select', SELECT_TOKENS],
    ['textarea', TEXTAREA_TOKENS],
    ['checkbox', CHECKBOX_TOKENS],
  ];

  return groups
    .map(([atom, states]) =>
      (Object.entries(states) as [FormControlState, FormControlTokenSet][])
        .map(([state, tokens]) =>
          [
            `.cl-${atom}--${state} {`,
            `  background: var(--cl-${tokens.background});`,
            `  color: var(--cl-${tokens.text});`,
            `  border-color: var(--cl-${tokens.border});`,
            '}',
          ].join('\n'),
        )
        .join('\n'),
    )
    .join('\n\n');
}

/** The `Modal`/`Dialog` organism's overlay and content-panel tokens. */
function dialog(): string {
  return [
    '.cl-dialog-backdrop {',
    `  background: var(--cl-${DIALOG_TOKENS.backdrop});`,
    '}',
    '',
    '.cl-dialog-surface {',
    `  background: var(--cl-${DIALOG_TOKENS.surface});`,
    `  border: 1px solid var(--cl-${DIALOG_TOKENS.border});`,
    `  box-shadow: ${DIALOG_TOKENS.elevation};`,
    '}',
  ].join('\n');
}

/**
 * Control-web's denser spacing composition, scoped to `[data-density="control"]`
 * so the exact same atoms render tighter there than on the marketing surfaces —
 * a composition choice, not a second component tree (design.md Decision 4).
 */
function density(): string {
  return [
    '[data-density="control"] {',
    ...Object.entries(CONTROL_DENSITY_SPACING).map(
      ([name, value]) => `  --cl-density-${name}: ${value};`,
    ),
    '}',
  ].join('\n');
}
