import {
  BREAKPOINTS,
  COLOR_PRIMITIVES,
  FONT_SIZE,
  FONT_WEIGHTS,
  MOTION,
  RADIUS,
  SPACING,
  TOUCH_TARGET,
  TYPOGRAPHY,
} from '../primitives.js';
import { BUTTON_VARIANTS, CARD_STATES, FOCUS_RING } from '../components.js';
import { SEMANTIC_COLORS, type SemanticColor } from '../semantic.js';

/**
 * CSS custom properties and component classes.
 *
 * Emitted as a plain stylesheet with no runtime: the public surfaces are Astro
 * and Starlight, and a token system that needed JavaScript to produce a colour
 * would be a token system that fails with JavaScript disabled — on the one
 * surface most likely to be behind a hotel proxy or on a venue TV.
 */

export function generateCss(): string {
  return [
    header(),
    `:root {`,
    ...Object.entries(COLOR_PRIMITIVES).map(([name, value]) => `  --cl-color-${name}: ${value};`),
    '',
    ...Object.entries(SEMANTIC_COLORS).map(
      ([name, token]) => `  --cl-${name}: var(--cl-color-${token.primitive});`,
    ),
    '',
    `  --cl-font-display: ${TYPOGRAPHY.display};`,
    `  --cl-font-body: ${TYPOGRAPHY.body};`,
    `  --cl-font-mono: ${TYPOGRAPHY.mono};`,
    ...Object.entries(FONT_WEIGHTS).map(([name, value]) => `  --cl-weight-${name}: ${value};`),
    ...Object.entries(FONT_SIZE).map(([name, value]) => `  --cl-font-size-${name}: ${value};`),
    '',
    ...Object.entries(SPACING).map(([name, value]) => `  --cl-space-${name}: ${value};`),
    ...Object.entries(RADIUS).map(([name, value]) => `  --cl-radius-${name}: ${value};`),
    ...Object.entries(BREAKPOINTS).map(([name, value]) => `  --cl-breakpoint-${name}: ${value};`),
    '',
    ...Object.entries(MOTION).map(([name, value]) => `  --cl-motion-${name}: ${value};`),
    `  --cl-touch-target: ${TOUCH_TARGET};`,
    `}`,
    '',
    reducedMotion(),
    '',
    chamfer(),
    '',
    imageFrame(),
    '',
    components(),
  ].join('\n');
}

function header(): string {
  return [
    '/* Generated by @copalibre/design-tokens. Do not edit by hand. */',
    '/* Source of truth: packages/design-tokens/src/primitives.ts */',
    '',
  ].join('\n');
}

/**
 * Under reduced motion every duration becomes zero.
 *
 * Overridden at the custom-property level rather than per component, so a
 * component added later inherits the behaviour instead of having to remember
 * it.
 */
function reducedMotion(): string {
  return [
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    `    --cl-motion-fast: ${MOTION.instant};`,
    `    --cl-motion-base: ${MOTION.instant};`,
    `    --cl-motion-slow: ${MOTION.instant};`,
    '  }',
    '',
    '  *, *::before, *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '  }',
    '}',
  ].join('\n');
}

/**
 * The chamfered corner, and the square one it falls back to.
 *
 * `corner-shape: bevel` where it exists, `clip-path` where it does not, and a
 * plain rectangle where neither does. The fallback is square rather than
 * rounded because a wrong-radius corner reads as a rendering bug, while a
 * square one reads as a deliberate, plainer surface.
 */
function chamfer(): string {
  return [
    '.cl-chamfer {',
    `  --cl-chamfer-size: ${RADIUS.chamfer};`,
    '  border-radius: 0;',
    '}',
    '',
    '@supports (clip-path: polygon(0 0)) {',
    '  .cl-chamfer {',
    '    clip-path: polygon(',
    '      var(--cl-chamfer-size) 0%, 100% 0%,',
    '      100% calc(100% - var(--cl-chamfer-size)),',
    '      calc(100% - var(--cl-chamfer-size)) 100%,',
    '      0% 100%, 0% var(--cl-chamfer-size)',
    '    );',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-chamfer {',
    '    clip-path: none;',
    '    corner-shape: bevel;',
    '    border-radius: var(--cl-chamfer-size);',
    '  }',
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-chamfer--control {',
    `  --cl-chamfer-size: ${RADIUS['chamfer-control']};`,
    '}',
  ].join('\n');
}

/**
 * A fixed 4:5 frame for a profile image (organization/club emblem, person
 * picture) or its placeholder — chamfered the same way `.cl-chamfer` already
 * is, `object-fit: cover` so a source whose stored aspect isn't exactly 4:5
 * (an image saved before this existed) still fills the frame without
 * distortion (0122).
 */
function imageFrame(): string {
  return [
    '.cl-image-frame {',
    `  --cl-chamfer-size: ${RADIUS['image-frame']};`,
    '  aspect-ratio: 4 / 5;',
    '  max-height: 512px;',
    '  border: 1px solid var(--cl-border-muted);',
    '  border-radius: 0;',
    '  overflow: hidden;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: var(--cl-surface-raised);',
    '}',
    '',
    '.cl-image-frame img {',
    '  width: 100%;',
    '  height: 100%;',
    '  object-fit: cover;',
    '  display: block;',
    '}',
    '',
    '.cl-image-frame svg {',
    '  width: 55%;',
    '  height: 55%;',
    '}',
    '',
    '@supports (clip-path: polygon(0 0)) {',
    '  .cl-image-frame {',
    '    clip-path: polygon(',
    '      var(--cl-chamfer-size) 0%, 100% 0%,',
    '      100% calc(100% - var(--cl-chamfer-size)),',
    '      calc(100% - var(--cl-chamfer-size)) 100%,',
    '      0% 100%, 0% var(--cl-chamfer-size)',
    '    );',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-image-frame {',
    '    clip-path: none;',
    '    corner-shape: bevel;',
    '    border-radius: var(--cl-chamfer-size);',
    '  }',
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-image-frame--control {',
    `  --cl-chamfer-size: ${RADIUS['image-frame-control']};`,
    '}',
  ].join('\n');
}

function components(): string {
  const cards = CARD_STATES.map(
    (state: SemanticColor) =>
      `.cl-card--${state.replace('state-', '')} { border-left-color: var(--cl-${state}); }`,
  );

  const buttons = Object.entries(BUTTON_VARIANTS).map(([variant, tokens]) =>
    [
      `.cl-btn--${variant} {`,
      `  background: ${tokens.background === 'transparent' ? 'transparent' : `var(--cl-${tokens.background})`};`,
      `  color: var(--cl-${tokens.text});`,
      `  border-color: ${tokens.border === 'transparent' ? 'transparent' : `var(--cl-${tokens.border})`};`,
      '}',
    ].join('\n'),
  );

  return [
    '.cl-card {',
    '  background: var(--cl-surface-panel);',
    '  color: var(--cl-text-primary);',
    '  border-left: var(--cl-space-1) solid var(--cl-border-muted);',
    '  padding: var(--cl-space-4);',
    '}',
    ...cards,
    '',
    '/* A badge is a colour *and* a label; the token contract refuses one without. */',
    '.cl-badge {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-1);',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-semibold);',
    '  text-transform: uppercase;',
    '  padding: var(--cl-space-1) var(--cl-space-2);',
    '}',
    '',
    '.cl-btn {',
    '  min-height: var(--cl-touch-target);',
    '  min-width: var(--cl-touch-target);',
    '  font-family: var(--cl-font-body);',
    '  font-weight: var(--cl-weight-semibold);',
    '  border: 1px solid transparent;',
    '  padding: var(--cl-space-2) var(--cl-space-4);',
    '  transition: background var(--cl-motion-fast) var(--cl-motion-easing);',
    '}',
    ...buttons,
    '',
    '.cl-inline-alert {',
    '  display: flex;',
    '  gap: var(--cl-space-2);',
    '  padding: var(--cl-space-3);',
    '  border-left: var(--cl-space-1) solid var(--cl-state-upcoming);',
    '  background: var(--cl-surface-raised);',
    '}',
    '',
    '.cl-stat-tile {',
    '  background: var(--cl-surface-raised);',
    '  padding: var(--cl-space-4);',
    '}',
    '',
    '.cl-stat-tile__value {',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-bold);',
    '  /* Scores that shift width as they change are scores nobody can read. */',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '',
    '.cl-focusable:focus-visible {',
    '  outline: none;',
    `  box-shadow: 0 0 0 ${FOCUS_RING.innerWidth} var(--cl-surface-base),`,
    `    0 0 0 ${FOCUS_RING.outerWidth} var(--cl-focus-ring);`,
    '}',
  ].join('\n');
}
