import {
  BREAKPOINTS,
  FONT_SOURCE,
  TRACKING,
  COLOR_PRIMITIVES,
  CONTROL_DENSITY_SPACING,
  FONT_SIZE,
  FONT_WEIGHTS,
  MOTION,
  RADIUS,
  SPACING,
  TOUCH_TARGET,
  TYPOGRAPHY,
} from '../primitives.js';
import {
  BUTTON_VARIANTS,
  CARD_STATES,
  CHECKBOX_TOKENS,
  DIALOG_TOKENS,
  FOCUS_RING,
  INPUT_TOKENS,
  SELECT_TOKENS,
  TEXTAREA_TOKENS,
  type FormControlState,
  type FormControlTokenSet,
} from '../components.js';
import { SEMANTIC_COLORS, type SemanticColor } from '../semantic.js';

/**
 * CSS custom properties and component classes.
 *
 * Emitted as a plain stylesheet with no runtime: the public surfaces are Astro
 * and Starlight, and a token system that needed JavaScript to produce a colour
 * would be a token system that fails with JavaScript disabled — on the one
 * surface most likely to be behind a hotel proxy or on a venue TV.
 */

export function generateCss(): string {
  return [
    /*
     * First, and before any rule: CSS requires `@import` to precede everything
     * but `@charset`, and a browser drops one that appears later.
     *
     * It lives here rather than in each layout's `<head>` because this session
     * found the same defect four times — styling that only one layout loaded,
     * so every other surface silently went without it. Every surface already
     * imports this stylesheet; none of them can forget to.
     */
    `@import url('${FONT_SOURCE}');`,
    '',
    header(),
    `:root {`,
    ...Object.entries(COLOR_PRIMITIVES).map(([name, value]) => `  --cl-color-${name}: ${value};`),
    '',
    ...Object.entries(SEMANTIC_COLORS).map(
      ([name, token]) => `  --cl-${name}: var(--cl-color-${token.primitive});`,
    ),
    '',
    `  --cl-font-display: ${TYPOGRAPHY.display};`,
    `  --cl-font-body: ${TYPOGRAPHY.body};`,
    `  --cl-font-mono: ${TYPOGRAPHY.mono};`,
    ...Object.entries(FONT_WEIGHTS).map(([name, value]) => `  --cl-weight-${name}: ${value};`),
    ...Object.entries(FONT_SIZE).map(([name, value]) => `  --cl-font-size-${name}: ${value};`),
    ...Object.entries(TRACKING).map(([name, value]) => `  --cl-tracking-${name}: ${value};`),
    '',
    ...Object.entries(SPACING).map(([name, value]) => `  --cl-space-${name}: ${value};`),
    ...Object.entries(RADIUS).map(([name, value]) => `  --cl-radius-${name}: ${value};`),
    ...Object.entries(BREAKPOINTS).map(([name, value]) => `  --cl-breakpoint-${name}: ${value};`),
    '',
    ...Object.entries(MOTION).map(([name, value]) => `  --cl-motion-${name}: ${value};`),
    `  --cl-touch-target: ${TOUCH_TARGET};`,
    // Derived from the action role rather than restating its channels: a glow
    // that keeps its own copy of the accent stops matching the moment 0220
    // calibrates `--cl-primary`.
    `  --cl-glow-cyan: 0 0 20px color-mix(in srgb, var(--cl-primary) 40%, transparent);`,
    `}`,
    '',
    reducedMotion(),
    '',
    chamfer(),
    '',
    imageFrame(),
    '',
    tacticalGrid(),
    '',
    components(),
    '',
    surfaceLevels(),
    '',
    formControls(),
    '',
    dialog(),
    '',
    density(),
  ].join('\n');
}

function header(): string {
  return [
    '/* Generated by @copalibre/design-tokens. Do not edit by hand. */',
    '/* Source of truth: packages/design-tokens/src/primitives.ts */',
    '',
  ].join('\n');
}

/**
 * Under reduced motion every duration becomes zero.
 *
 * Overridden at the custom-property level rather than per component, so a
 * component added later inherits the behaviour instead of having to remember
 * it.
 */
function reducedMotion(): string {
  return [
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    `    --cl-motion-fast: ${MOTION.instant};`,
    `    --cl-motion-base: ${MOTION.instant};`,
    `    --cl-motion-slow: ${MOTION.instant};`,
    '  }',
    '',
    '  *, *::before, *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '  }',
    '}',
  ].join('\n');
}

/**
 * Surface levels, assigned from what a container is rather than how deep it sits.
 *
 * The reference project layers in both directions inside one composition:
 * `ExplainableStandingsDemo` puts its card at `ink-950` under an `ink-900` band,
 * while `AuditedResultsDemo` puts the same shape at `ink-900` over an `ink-950`
 * band. So content *alternates* against whatever it sits on. Chrome does not —
 * both lift their header and chips to `ink-850` regardless of depth.
 *
 * Written as zero-specificity `:where()` rules so a component's own state rules
 * (selected, error, hover) still win without `!important`, and so the same rule
 * governs Astro markup and React islands — the only layer both renderers share.
 */
function surfaceLevels(): string {
  return [
    // Every level rule is zero-specificity and ordered from general to
    // specific, so the cascade resolves them by intent rather than by weight.
    ':where(.cl-card, .cl-well) { background: var(--cl-surface-panel); }',
    '',
    '/* A band names the level its children alternate against. */',
    '.cl-band { --cl-content-level: panel; background: var(--cl-surface-panel); }',
    '.cl-band--base { --cl-content-level: base; background: var(--cl-surface-base); }',
    '',
    // The alternation itself: a content container inside a panel-level band
    // drops to base, and one inside a base-level band lifts to panel. Two flat
    // rules rather than a counter, because direction is what matters and a
    // miscounted depth is invisible until someone notices the wrong shade.
    ':where(.cl-band) :where(.cl-card, .cl-well) { background: var(--cl-surface-base); }',
    ':where(.cl-band--base) :where(.cl-card, .cl-well) { background: var(--cl-surface-panel); }',
    ':where(.cl-card) :where(.cl-well) { background: var(--cl-surface-panel); }',
    ':where(.cl-band--base) :where(.cl-card) :where(.cl-well) { background: var(--cl-surface-base); }',
    '',
    // Style queries read the parent's inherited level, including through
    // layout wrappers. Each content surface then supplies the opposite level
    // to its descendants, so the alternation has no hardcoded depth limit.
    ':where(.cl-card, .cl-well) { --cl-content-level: panel; }',
    '@container style(--cl-content-level: panel) {',
    '  :where(.cl-card, .cl-well) { --cl-content-level: base; background: var(--cl-surface-base); }',
    '}',
    '@container style(--cl-content-level: base) {',
    '  :where(.cl-card, .cl-well) { --cl-content-level: panel; background: var(--cl-surface-panel); }',
    '}',
    '',
    '/* Chrome lifts wherever it sits, so a header reads as a header at any depth. */',
    ':where(.cl-chrome, .cl-card__header, .cl-card__footer) { background: var(--cl-surface-chrome); }',
    '',
    // Every boundary carries the border the semantic contract already requires
    // of a panel, so two levels never rely on their fill difference alone.
    ':where(.cl-card, .cl-well, .cl-chrome, .cl-card__header, .cl-card__footer) { border: 1px solid var(--cl-border-muted); }',
    '',
    "/* Rows alternate as opaque roles, so a row's contrast is checkable. */",
    '.cl-row { background: var(--cl-surface-row); }',
    '.cl-row--alt { background: var(--cl-surface-row-alt); }',
    // A figure that changes width as it updates is a column nobody can scan.
    '.cl-row__figure { font-variant-numeric: tabular-nums; text-align: right; }',
  ].join('\n');
}

/**
 * The signature asymmetric chamfered corner.
 *
 * One diagonal pair is cut — top-right and bottom-left at `--cl-chamfer-size`,
 * top-left and bottom-right square.
 *
 * Exclusively driven by `corner-shape: bevel` and `border-radius`:
 * `border-radius: 0 var(--cl-chamfer-size) 0 var(--cl-chamfer-size)`.
 * No `clip-path` is used, ensuring borders, outlines, box-shadow glows and
 * focus rings render intact without being clipped.
 */
function chamfer(): string {
  const size = 'var(--cl-chamfer-size)';
  return [
    '.cl-chamfer, .cl-chamfer-tr, .cl-chamfer-bl {',
    `  --cl-chamfer-size: ${RADIUS.chamfer};`,
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-chamfer--control {',
    `  --cl-chamfer-size: ${RADIUS['chamfer-control']};`,
    '}',
    '',
    // Two tiers rather than one. A browser that has only the per-corner
    // longhands still bevels; without this it would fall all the way back to
    // square while supporting the geometry perfectly well.
    '@supports (corner-top-right-shape: bevel) or (corner-shape: bevel) {',
    '  .cl-chamfer-tr {',
    '    border-radius: 0;',
    `    border-top-right-radius: ${size};`,
    '    corner-top-right-shape: bevel;',
    '  }',
    '  .cl-chamfer-bl {',
    '    border-radius: 0;',
    `    border-bottom-left-radius: ${size};`,
    '    corner-bottom-left-shape: bevel;',
    '  }',
    '  .cl-chamfer, .cl-chamfer--control {',
    '    border-radius: 0;',
    `    border-top-right-radius: ${size};`,
    `    border-bottom-left-radius: ${size};`,
    '    corner-top-right-shape: bevel;',
    '    corner-bottom-left-shape: bevel;',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-chamfer-tr {',
    `    border-radius: 0 ${size} 0 0;`,
    '    corner-shape: round bevel round round;',
    '  }',
    '  .cl-chamfer-bl {',
    `    border-radius: 0 0 0 ${size};`,
    '    corner-shape: round round round bevel;',
    '  }',
    '  .cl-chamfer, .cl-chamfer--control {',
    `    border-radius: 0 ${size} 0 ${size};`,
    '    corner-shape: round bevel round bevel;',
    '  }',
    '}',
  ].join('\n');
}

/**
 * A fixed 4:5 frame for a profile image (organization/club emblem, person
 * picture) or its placeholder — chamfered the same way `.cl-chamfer` already
 * is, `object-fit: cover` so a source whose stored aspect isn't exactly 4:5
 * still fills the frame without distortion.
 */
function imageFrame(): string {
  return [
    '.cl-image-frame {',
    `  --cl-chamfer-size: ${RADIUS['image-frame']};`,
    '  aspect-ratio: 4 / 5;',
    '  max-height: 512px;',
    '  border: 1px solid var(--cl-border-muted);',
    '  overflow: hidden;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: var(--cl-surface-raised);',
    '  corner-shape: bevel;',
    '  border-radius: 0 var(--cl-chamfer-size) 0 var(--cl-chamfer-size);',
    '}',
    '',
    '.cl-image-frame img {',
    '  width: 100%;',
    '  height: 100%;',
    '  object-fit: cover;',
    '  display: block;',
    '}',
    '',
    '.cl-image-frame svg {',
    '  width: 55%;',
    '  height: 55%;',
    '}',
    '',
    '/* Operator surfaces cut less: density over drama. */',
    '.cl-image-frame--control {',
    `  --cl-chamfer-size: ${RADIUS['image-frame-control']};`,
    '}',
  ].join('\n');
}

/**
 * Coordinate grid utility for tournament brackets, heroes, and tactical backdrops.
 */
function tacticalGrid(): string {
  return [
    '.cl-tactical-grid {',
    '  background-image:',
    '    linear-gradient(to right, color-mix(in srgb, var(--cl-primary) 6%, transparent) 1px, transparent 1px),',
    '    linear-gradient(to bottom, color-mix(in srgb, var(--cl-primary) 6%, transparent) 1px, transparent 1px);',
    '  background-size: var(--cl-space-6) var(--cl-space-8);',
    '}',
  ].join('\n');
}

function components(): string {
  const cards = CARD_STATES.map(
    (state: SemanticColor) =>
      `.cl-card--${state.replace('state-', '')} { border-left-color: var(--cl-${state}); }`,
  );

  const buttons = Object.entries(BUTTON_VARIANTS).map(([variant, tokens]) =>
    [
      `.cl-btn--${variant} {`,
      `  background: ${tokens.background === 'transparent' ? 'transparent' : `var(--cl-${tokens.background})`};`,
      `  color: var(--cl-${tokens.text});`,
      `  border-color: ${tokens.border === 'transparent' ? 'transparent' : `var(--cl-${tokens.border})`};`,
      '}',
    ].join('\n'),
  );

  // A variant that states its hovered fill gets it from the contract; the
  // brightness filter below stays for the ones that do not, so a hover is
  // never left to chance.
  const buttonHovers = Object.entries(BUTTON_VARIANTS)
    .filter(([, tokens]) => tokens.hover !== undefined)
    .map(([variant, tokens]) => {
      const hover = tokens.hover as NonNullable<typeof tokens.hover>;
      return [
        `.cl-btn--${variant}:hover:not(:disabled) {`,
        `  background: var(--cl-${hover.background});`,
        ...(hover.border === undefined ? [] : [`  border-color: var(--cl-${hover.border});`]),
        '  filter: none;',
        '}',
      ].join('\n');
    });

  return [
    // No `background` here: a card's level comes from what it sits on, which
    // `surfaceLevels()` decides. A fixed value at this specificity would beat
    // those zero-specificity rules and pin every card to one shade.
    '.cl-card {',
    '  color: var(--cl-text-primary);',
    '  border-left: var(--cl-space-1) solid var(--cl-border-muted);',
    '  padding: var(--cl-space-4);',
    '}',
    ...cards,
    '',
    '.cl-card__header { display: grid; gap: var(--cl-space-1); margin-block-end: var(--cl-space-3); }',
    // A card's title is often a single long compound — `Turniereinstellungen`,
    // `Plattformverwaltung` — which has no break opportunity and sets the
    // card's min-content width above the viewport at the 188px reference,
    // pushing the page sideways. The same treatment the match-console titles
    // already carry, for the same reason.
    '.cl-card__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-card__description { margin: 0; color: var(--cl-text-muted); }',
    '.cl-card__content { display: grid; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-card__footer { display: flex; gap: var(--cl-space-2); margin-block-start: var(--cl-space-4); }',
    '',
    '.cl-input, .cl-select, .cl-textarea {',
    '  min-height: var(--cl-touch-target);',
    '  font-family: var(--cl-font-body);',
    '  border: 1px solid;',
    '  padding: var(--cl-space-2) var(--cl-space-3);',
    // A bare <input>/<select>/<textarea> has a UA-stylesheet intrinsic
    // min-content width (Chromium: roughly a `size=20` input) that a narrow
    // grid track cannot override without an explicit width — without this,
    // the control forces its own grid ancestor wider than the viewport at
    // the narrowest reference width (188px, a 200%-zoom equivalent).
    '  width: 100%;',
    '  min-width: 0;',
    '  color-scheme: dark;',
    '}',
    '',
    /*
     * The same diagonal cut the chamfer utility makes, on the controls
     * themselves rather than on a wrapper.
     *
     * `corner-shape` only, with no `clip-path` fallback: these carry
     * `.cl-focusable`, whose focus ring is a `box-shadow`, and `clip-path`
     * clips box-shadows away. A browser without `corner-shape` therefore keeps
     * square controls and a visible focus ring, which is the right way round —
     * the fallback philosophy is already "a plain rectangle where neither
     * works", and a focus indicator is not decoration to trade for a bevel.
     */
    '@supports (corner-shape: bevel) {',
    '  .cl-input, .cl-select, .cl-textarea {',
    '    corner-shape: bevel;',
    '    border-radius: 0 var(--cl-radius-chamfer-control) 0 var(--cl-radius-chamfer-control);',
    '  }',
    '}',
    '',
    '.cl-input::-webkit-calendar-picker-indicator {',
    '  filter: invert(0.8);',
    '  cursor: pointer;',
    '}',
    '',
    '.cl-input[type="file"] {',
    '  padding: var(--cl-space-1);',
    '}',
    '.cl-input[type="file"]::file-selector-button {',
    '  background: var(--cl-surface-raised);',
    '  color: var(--cl-text-primary);',
    '  border: 1px solid var(--cl-border-muted);',
    '  padding: var(--cl-space-1) var(--cl-space-3);',
    '  margin-right: var(--cl-space-3);',
    '  font-family: var(--cl-font-body);',
    '  font-size: var(--cl-font-size-sm);',
    '  cursor: pointer;',
    '  border-radius: var(--cl-radius-sm);',
    '  transition: background 120ms ease;',
    '}',
    '.cl-input[type="file"]::file-selector-button:hover {',
    '  background: var(--cl-surface-hover);',
    '}',
    '',
    '.cl-checkbox {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: var(--cl-touch-target);',
    '  height: var(--cl-touch-target);',
    '  border: 1px solid;',
    '}',
    'input[type="checkbox"].cl-checkbox, input[type="radio"] {',
    '  appearance: none;',
    '  -webkit-appearance: none;',
    '  width: 1.25rem;',
    '  height: 1.25rem;',
    '  min-height: 1.25rem;',
    '  min-width: 1.25rem;',
    '  margin: 0;',
    '  cursor: pointer;',
    '  border-radius: var(--cl-radius-sm);',
    '  background: var(--cl-surface-base);',
    '  border: 1px solid var(--cl-border-muted);',
    '  display: inline-grid;',
    '  place-content: center;',
    '  flex-shrink: 0;',
    '  color-scheme: dark;',
    '}',
    'input[type="checkbox"].cl-checkbox:hover, input[type="radio"]:hover {',
    '  border-color: var(--cl-border-hover);',
    '}',
    'input[type="checkbox"].cl-checkbox:checked, input[type="radio"]:checked {',
    '  background: var(--cl-state-live);',
    '  border-color: var(--cl-state-live);',
    '}',
    /*
     * A radio's mark is a square, not the checkbox's tick: the shape says
     * "one of these" where the tick says "this one is on", and a chamfered box
     * with a round dot inside would be two geometries arguing.
     */
    'input[type="radio"]:checked::before {',
    '  content: "";',
    '  width: 0.5rem;',
    '  height: 0.5rem;',
    '  background-color: var(--cl-color-ink-950);',
    '}',
    'input[type="checkbox"].cl-checkbox:checked::before {',
    '  content: "";',
    '  width: 0.55rem;',
    '  height: 0.55rem;',
    '  background-color: var(--cl-color-ink-950);',
    '  clip-path: polygon(14% 44%, 0 58%, 40% 98%, 100% 16%, 86% 2%, 40% 68%);',
    '}',
    'input[type="checkbox"].cl-checkbox:focus-visible {',
    '  outline: 2px solid var(--cl-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '',
    '.cl-toggle {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-2);',
    '  cursor: pointer;',
    '  user-select: none;',
    '}',
    '',
    '.cl-link {',
    '  color: var(--cl-state-live);',
    '  text-decoration: underline;',
    '  text-underline-offset: 4px;',
    '  cursor: pointer;',
    '  transition: opacity 120ms ease;',
    '}',
    '.cl-link:hover {',
    '  opacity: 0.85;',
    '}',
    '.cl-link:focus-visible {',
    '  outline: 2px solid var(--cl-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '.cl-checkbox__indicator { color: var(--cl-state-live); }',
    /*
     * Checkboxes and radios cut all four corners, unlike every other surface,
     * which cuts one diagonal pair. A 20px box carrying an asymmetric cut reads
     * as a rendering slip rather than a shape; symmetry is what makes it read
     * as deliberate at that size.
     *
     * `--cl-radius-md` (4px) rather than the 8px control chamfer: eight on a
     * twenty-pixel box leaves a diamond.
     */
    '@supports (corner-shape: bevel) {',
    // The 44px target the Checkbox atom renders — a Radix `<button
    // role="checkbox">`, not an `<input>`, so this keys on the class.
    '  .cl-checkbox {',
    '    corner-shape: bevel;',
    '    border-radius: var(--cl-radius-chamfer-control);',
    '  }',
    // The 20px native controls: a proportionate cut, because eight pixels off
    // each corner of a twenty-pixel box leaves a diamond.
    '  input[type="checkbox"].cl-checkbox, input[type="radio"] {',
    '    border-radius: var(--cl-radius-md);',
    '  }',
    '}',
    '.cl-select__icon { margin-inline-start: var(--cl-space-2); }',
    // `popper` positioning exposes the trigger's width, so the panel lines up
    // with the box it belongs to rather than sizing itself to its longest
    // option. `max-height` is the space Radix measured to the viewport edge.
    '.cl-select__content { padding: var(--cl-space-1); min-width: var(--radix-select-trigger-width); max-height: var(--radix-select-content-available-height); overflow-y: auto; }',
    '.cl-select__item { padding: var(--cl-space-2) var(--cl-space-3); cursor: pointer; }',
    '.cl-label { font-family: var(--cl-font-mono); text-transform: uppercase; font-size: var(--cl-font-size-xs); }',
    '',
    '.cl-form-field { display: grid; gap: var(--cl-space-1); min-width: 0; }',
    '.cl-form-field__error { margin: 0; color: var(--cl-state-destructive); font-size: var(--cl-font-size-xs); }',
    '.cl-form-field__help { margin: 0; color: var(--cl-text-muted); font-size: var(--cl-font-size-xs); }',
    '.cl-decision-hint { margin: 0; color: var(--cl-text-muted); font-size: var(--cl-font-size-xs); }',
    '',
    '.cl-data-entity-card__header { display: flex; align-items: center; justify-content: space-between; }',
    '.cl-data-entity-card__metadata { display: grid; gap: var(--cl-space-2); }',
    // `min-width: 0` on the row and a break opportunity on the label: a flex
    // item will not shrink below its own min-content width, so a long label
    // like `Austragungsorte & Offizielle` pushed the whole card past the 188px
    // reference width and scrolled the page sideways.
    '.cl-data-entity-card__metadata-item { display: flex; justify-content: space-between; gap: var(--cl-space-2); min-width: 0; }',
    '.cl-data-entity-card__metadata-label { color: var(--cl-text-muted); min-width: 0; overflow-wrap: anywhere; }',
    // The accent a DataEntityCard carries for its subject's lifecycle. `.cl-card`
    // already draws a left border in the muted token; an accent recolours that
    // one edge rather than adding a second treatment, so a card with an accent
    // and one without stay the same size. `muted` is the default made explicit,
    // which a call site needs when it wants to state "no state" rather than
    // omit the prop.
    //
    // These exist because the prop did not: `DataEntityCard` has emitted
    // `cl-state--<accent>` since it gained `accent`, and nothing defined the
    // class, so every accent rendered identically to none (found 2026-09-08 by
    // putting the four accents side by side in the workbench).
    '.cl-state--live { border-left-color: var(--cl-state-live); }',
    '.cl-state--upcoming { border-left-color: var(--cl-state-upcoming); }',
    '.cl-state--positive { border-left-color: var(--cl-state-positive); }',
    '.cl-state--muted { border-left-color: var(--cl-border-muted); }',
    // A card's counts read as figures, sized below the screen's summary tiles so
    // they never compete with its headline numbers.
    '.cl-data-entity-card__metadata-figure { font-family: var(--cl-font-mono); font-variant-numeric: tabular-nums; color: var(--cl-text-primary); }',
    // Tournaments are however many an organization has, so auto-fit — the same
    // rule the matches view already uses, not the fixed three of the summary tiles.
    // `min(100%, 280px)` rather than a bare 280px floor: a hard minimum wider
    // than the viewport makes the page itself scroll sideways, which the
    // responsive gate checks down to 188px. The same idiom the form grid uses.
    '.cl-entity-card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 280px), 1fr)); gap: var(--cl-space-4); }',
    // The footer ranks its actions: the primary and the grouped menu lead, the
    // destructive one is pushed to the end by the footer rather than by a margin
    // on the button, since no component below the template tier owns its own.
    '.cl-entity-card-actions { display: flex; align-items: center; gap: var(--cl-space-2); flex-wrap: wrap; width: 100%; }',
    '.cl-entity-card-actions__destructive { margin-inline-start: auto; }',
    '',
    '.cl-table-toolbar { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: var(--cl-space-3); }',
    // `min-width: 0` because a flex item refuses to shrink below its own
    // min-content width by default, and the break properties because a long
    // compound has no break opportunity to shrink to — both are needed, and
    // either alone still overflows at the 188px reference width.
    '.cl-table-toolbar__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; min-width: 0; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-table-toolbar__filters, .cl-table-toolbar__actions { display: flex; flex-wrap: wrap; gap: var(--cl-space-2); align-items: center; }',
    '',
    // Three touch targets plus their gaps exceed the 188px reference width on
    // their own, and a touch target is not negotiable — so the row wraps and
    // centres instead of overflowing. Above that width it is still one line.
    '.cl-pagination { display: flex; align-items: center; justify-content: center; flex-wrap: wrap; gap: var(--cl-space-3); }',
    '.cl-pagination__status { color: var(--cl-text-muted); font-family: var(--cl-font-mono); }',
    '',
    // `min-width: 0` and a break opportunity for the same reason the entity
    // card's metadata row needs them: a grid item will not shrink below its own
    // min-content width, and a value like an unhyphenated club name has no
    // break the browser will take on its own.
    '.cl-field-value { display: grid; gap: var(--cl-space-1); background: var(--cl-surface-base); padding: var(--cl-space-3); border: 1px solid var(--cl-border-muted); min-width: 0; overflow-wrap: anywhere; }',
    '.cl-field-value__label { display: block; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); min-width: 0; overflow-wrap: anywhere; }',
    '',
    '.cl-clock-ring { display: flex; align-items: center; gap: var(--cl-space-2); }',
    '',
    '.cl-data-table { padding: 0; overflow-x: auto; scrollbar-gutter: stable; }',
    '.cl-data-table__table { width: 100%; border-collapse: collapse; }',
    '.cl-data-table__table th { text-align: left; padding: var(--cl-space-3) var(--cl-space-4); border-bottom: 1px solid var(--cl-border-muted); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-data-table__table td { padding: var(--cl-space-3) var(--cl-space-4); }',
    '.cl-data-table__empty { padding: var(--cl-space-4); color: var(--cl-text-muted); }',
    '@media (max-width: 767px) { .cl-data-table { -webkit-overflow-scrolling: touch; } }',
    '',
    '.cl-modal__overlay { position: fixed; inset: 0; }',
    '.cl-modal__content { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); width: min(480px, calc(100vw - var(--cl-space-8))); max-height: 85vh; overflow-y: auto; padding: var(--cl-space-4); }',
    // The title and the close control share a row, and a long compound title
    // pushed the dialog past the 188px reference width. The same treatment the
    // card and toolbar titles already carry — this one was missed because the
    // workbench was rendering it inside a 240px column, where nothing could
    // overflow because nothing had room to try.
    '.cl-modal__header { display: flex; align-items: start; justify-content: space-between; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-modal__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; min-width: 0; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-modal__description { margin: 0; color: var(--cl-text-muted); }',
    '.cl-modal__close { background: transparent; border: 0; color: var(--cl-text-primary); }',
    '.cl-modal__body { margin-block: var(--cl-space-4); display: grid; gap: var(--cl-space-3); }',
    '.cl-modal__footer { display: flex; justify-content: flex-end; gap: var(--cl-space-2); }',
    '',
    // The menu surface reuses the dialog surface, since both are the same thing
    // — a layer floating over the screen — and a second definition of that would
    // be a second thing to keep in step.
    '.cl-dropdown-menu__content { min-width: 12rem; padding: var(--cl-space-1); display: grid; gap: 2px; z-index: 40; }',
    '.cl-dropdown-menu__item { padding: var(--cl-space-2) var(--cl-space-3); font-size: var(--cl-font-size-sm); color: var(--cl-text-primary); cursor: pointer; user-select: none; }',
    '.cl-dropdown-menu__item[data-highlighted] { background: var(--cl-surface-raised); outline: none; }',
    ".cl-dropdown-menu__item[data-variant='destructive'] { color: var(--cl-state-destructive); }",
    '.cl-dropdown-menu__item[data-disabled] { color: var(--cl-text-muted); pointer-events: none; }',
    '',
    '/* Templates own inter-section spacing (design.md Decision 7) — no component below this tier sets its own external margin. */',
    '.cl-list-screen, .cl-form-screen, .cl-match-console-screen { display: grid; gap: var(--cl-density-section-gap, var(--cl-space-6)); min-width: 0; }',
    // A grid item's default `min-width: auto` sizes it to its content, which
    // silently defeats a descendant's `overflow-x: auto` (a wide table forces
    // every ancestor grid track wider instead of scrolling in place). Every
    // grid track in this template chain gets `min-width: 0` so the narrowest
    // reference width (188px, a 200%-zoom equivalent) scrolls instead of
    // overflowing the page.
    '.cl-list-screen > *, .cl-form-screen > *, .cl-match-console-screen > * { min-width: 0; }',
    '.cl-list-screen__header, .cl-form-screen__header { display: flex; align-items: end; justify-content: space-between; gap: var(--cl-space-4); flex-wrap: wrap; }',
    '.cl-list-screen__title, .cl-form-screen__title { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; }',
    '.cl-list-screen__breadcrumb, .cl-form-screen__breadcrumb { color: var(--cl-state-live); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-form-screen__section { display: grid; gap: var(--cl-space-3); }',
    '.cl-form-screen__section-heading { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; font-size: var(--cl-font-size-lg); }',
    '.cl-form-screen__section-fields { display: grid; gap: var(--cl-space-4); }',
    '.cl-form-screen__footer { position: sticky; bottom: 0; display: flex; justify-content: flex-end; gap: var(--cl-space-2); padding-block: var(--cl-space-3); background: var(--cl-surface-base); }',
    '.cl-list-screen__empty { margin: 0; padding: var(--cl-space-5); color: var(--cl-text-muted); }',
    '',
    '/* The unauthenticated screens: brand header, one centred panel, and the page gutter that keeps it off the viewport edge at every width. */',
    '.cl-auth-screen { display: grid; grid-template-rows: auto 1fr; min-height: 100vh; min-width: 0; max-width: 100%; padding: clamp(24px, 5vw, 64px); font-family: var(--cl-font-body); overflow-wrap: anywhere; }',
    '.cl-auth-screen__header { display: flex; align-items: center; gap: var(--cl-space-3); }',
    '.cl-auth-screen__mark { border: 1px solid var(--cl-state-live); padding: var(--cl-space-1); }',
    '.cl-auth-screen__brand { display: grid; gap: 2px; }',
    '.cl-auth-screen__wordmark { font-family: var(--cl-font-display); font-size: var(--cl-font-size-md); }',
    '.cl-auth-screen__tagline { color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    // The live-accent rail is the auth surface's own identity, kept exactly as
    // the shipped login/forgot/reset screens carry it. A Card composed inside
    // this panel sits 24px inboard of it, so the two read as a rail plus a
    // card rather than a doubled border.
    '.cl-auth-screen__panel { width: min(100%, 560px); min-width: 0; max-width: 100%; box-sizing: border-box; align-self: center; margin-block: var(--cl-space-8); display: grid; gap: var(--cl-space-5); border-left: 4px solid var(--cl-state-live); padding: var(--cl-space-6) 0 var(--cl-space-6) var(--cl-space-6); }',
    '',
    '.cl-match-console-screen__header { display: flex; justify-content: space-between; align-items: start; gap: var(--cl-space-4); flex-wrap: wrap; min-width: 0; }',
    '.cl-match-console-screen__header > * { min-width: 0; }',
    '.cl-match-console-screen__title { margin: var(--cl-space-1) 0 0; font-family: var(--cl-font-display); text-transform: uppercase; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-match-console-screen__breadcrumb { color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; margin: 0; overflow-wrap: anywhere; word-break: break-word; }',
    '.cl-match-console-screen__status { display: grid; justify-items: end; color: var(--cl-state-live); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); min-width: 0; overflow-wrap: anywhere; }',
    '.cl-match-console-screen__sync-status { display: flex; min-width: 0; }',
    // One dot, and the detail only while the operator asks for it. The detail
    // is absolutely positioned so disclosing it never reflows the controls
    // underneath — a console that shifts under a moving hand loses taps.
    '.cl-sync-indicator { position: relative; display: inline-flex; }',
    '.cl-sync-indicator__icon { display: grid; place-items: center; width: 24px; height: 24px; }',
    '.cl-sync-indicator__dot { width: 10px; height: 10px; border-radius: 50%; background: currentColor; }',
    '.cl-sync-indicator__icon--online { color: var(--cl-state-live); }',
    '.cl-sync-indicator__icon--offline { color: var(--cl-text-muted); }',
    '.cl-sync-indicator__icon--offline .cl-sync-indicator__dot { background: transparent; border: 2px solid currentColor; }',
    '.cl-sync-indicator__detail { position: absolute; top: 100%; left: 0; z-index: 2; display: grid; gap: var(--cl-space-1); white-space: nowrap; border: 1px solid var(--cl-border-muted); background: var(--cl-surface-panel); padding: var(--cl-space-2) var(--cl-space-3); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    // Wraps rather than scrolls: on a phone held sideways at the touchline the
    // three clock commands must all stay reachable without a horizontal swipe.
    '.cl-clock-commands { display: flex; flex-wrap: wrap; gap: var(--cl-space-3); }',
    '.cl-match-console-screen__workspace { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr)); gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__workspace > * { min-width: 0; }',
    '@media (max-width: 600px) { .cl-match-console-screen__workspace { grid-template-columns: 1fr; } }',
    '.cl-match-console-screen__primary { display: grid; align-content: start; gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__rail { display: grid; align-content: start; gap: var(--cl-space-5); min-width: 0; }',
    '.cl-match-console-screen__scoreboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 120px), 1fr)); border: 1px solid var(--cl-border-muted); background: var(--cl-surface-panel); min-width: 0; }',
    '.cl-match-console-screen__score-side { display: flex; justify-content: space-between; align-items: center; gap: var(--cl-space-3); padding: var(--cl-space-4); font-family: var(--cl-font-mono); font-variant-numeric: tabular-nums; font-size: var(--cl-font-size-lg); min-width: 0; }',
    '.cl-match-console-screen__score-entrant { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
    '',
    '/* A row-identity chip (avatar initials + label) reused by any listing showing one person per row. */',
    '.cl-role-user { display: flex; align-items: center; gap: var(--cl-space-3); min-width: 0; flex-wrap: wrap; }',
    '.cl-role-user__avatar { display: grid; place-items: center; width: 32px; height: 32px; flex: 0 0 32px; background: var(--cl-surface-raised); border: 1px solid var(--cl-border-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    // An email address has no break opportunity a browser will take by
    // default, so the identity column set a min-content width wider than the
    // 188px reference. `anywhere` rather than `break-word`: the address must
    // break mid-token, since it is one token.
    '.cl-role-user > span { min-width: 0; overflow-wrap: anywhere; }',
    '.cl-role-user__id { display: block; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    '.cl-role-status { display: flex; align-items: center; gap: var(--cl-space-2); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-role-status--active { color: var(--cl-state-live); }',
    '.cl-role-status--inactive { color: var(--cl-text-muted); }',
    '',
    // One name for one rule. The dashboard's and the platform screen's own
    // section wrappers were byte-identical: a screen that stacks sections is a
    // screen that stacks sections, whichever screen it is.
    '.cl-screen-sections { display: grid; gap: var(--cl-density-section-gap, var(--cl-space-6)); min-width: 0; }',
    '.cl-screen-sections > * { min-width: 0; }',
    '/* The dashboard activity feed renders through DataTable; these are the cell treatments its rows carry. */',
    '.cl-activity-feed { display: grid; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-activity-feed > h2 { margin: 0; font-family: var(--cl-font-display); text-transform: uppercase; font-size: var(--cl-font-size-lg); }',
    '.cl-activity-feed__action-code, .cl-activity-feed__reason { color: var(--cl-text-muted); font-family: var(--cl-font-mono); }',
    '.cl-activity-feed__reason { font-size: var(--cl-font-size-sm); }',
    // An actor id, an action code and a relative time are single tokens: broken
    // mid-word they stop being readable at all. Kept whole, the table overflows
    // into the scroll its own region already provides.
    '.cl-activity-feed__action-code, .cl-activity-feed__time, .cl-activity-feed .cl-badge { white-space: nowrap; overflow-wrap: normal; }',
    '.cl-platform-form-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 210px), 1fr)); gap: var(--cl-space-4); align-items: end; }',
    '.cl-platform-update-list { margin: 0; padding: var(--cl-space-4); list-style-position: inside; border: 1px solid var(--cl-state-upcoming); color: var(--cl-text-secondary); }',
    '.cl-platform-modules-header { display: flex; justify-content: space-between; align-items: start; gap: var(--cl-space-4); flex-wrap: wrap; }',
    '/* A badge is a colour *and* a label; the token contract refuses one without. */',
    /*
     * The badge's chamfer is a stated exception, and a deliberate divergence:
     * the reference project paints badges square, with no chamfer class at any
     * call site. The inherited diagonal pair is worse than either — at badge
     * proportions its two cuts land at opposite ends of a short label and the
     * result reads as a skewed box rather than as the motif. Cutting the left
     * pair reads as a tag; cutting all four would read as a pill.
     */
    '.cl-badge {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-1);',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-semibold);',
    '  text-transform: uppercase;',
    '  padding: var(--cl-space-1) var(--cl-space-2);',
    '}',
    '',
    '@supports (corner-top-left-shape: bevel) or (corner-shape: bevel) {',
    '  .cl-badge {',
    '    border-radius: 0;',
    '    border-top-left-radius: var(--cl-radius-chamfer);',
    '    border-bottom-left-radius: var(--cl-radius-chamfer);',
    '    corner-top-left-shape: bevel;',
    '    corner-bottom-left-shape: bevel;',
    '  }',
    '}',
    '',
    '@supports (corner-shape: bevel) {',
    '  .cl-badge {',
    '    border-radius: var(--cl-radius-chamfer) 0 0 var(--cl-radius-chamfer);',
    '    corner-shape: bevel round round bevel;',
    '  }',
    '}',
    '',
    '.cl-btn {',
    '  min-height: var(--cl-touch-target);',
    '  min-width: var(--cl-touch-target);',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-bold);',
    '  text-transform: uppercase;',
    '  letter-spacing: var(--cl-tracking-wider);',
    '  border: 1px solid transparent;',
    '  padding: var(--cl-space-2) var(--cl-space-4);',
    '  transition: background var(--cl-motion-fast) var(--cl-motion-easing), box-shadow var(--cl-motion-fast) var(--cl-motion-easing), filter var(--cl-motion-fast) var(--cl-motion-easing);',
    // A label of two words wraps on its space and fits; a single compound —
    // `Turniereinstellungen` — has no break the browser will take, so the
    // button grew past the 188px reference width and pushed the page sideways.
    '  max-width: 100%;',
    '  overflow-wrap: anywhere;',
    '  corner-shape: bevel;',
    '  border-radius: 0 var(--cl-radius-chamfer-control) 0 var(--cl-radius-chamfer-control);',
    '}',
    ...buttons,
    '',
    '/* A control reads as pressable through its own states, not only its fill. */',
    '.cl-btn:hover:not(:disabled) { filter: brightness(1.12); }',
    ...buttonHovers,
    '.cl-btn:active:not(:disabled) { filter: brightness(0.92); }',
    '.cl-btn--primary:hover:not(:disabled),',
    '.cl-btn--primary:active:not(:disabled) {',
    '  box-shadow: var(--cl-glow-cyan);',
    '}',
    '.cl-btn:disabled {',
    '  opacity: 0.55;',
    '  cursor: not-allowed;',
    '  filter: none;',
    '}',
    '',
    /*
     * The public (Persuade) treatment: the display face, uppercase, tracked out.
     * Operator screens keep body type — a dense console label like "Exportar
     * configuración JSON" is harder to read in caps, not easier.
     */
    '.cl-btn--persuade {',
    '  font-family: var(--cl-font-display);',
    '  text-transform: uppercase;',
    '  letter-spacing: var(--cl-tracking-widest);',
    '  font-weight: var(--cl-weight-bold);',
    '}',
    '',
    /*
     * One table treatment for every surface that shows tabular data. Figures
     * are tabular-numeric table-wide: a standings column whose digits shift
     * width as scores change is a column nobody can scan down.
     */
    '.cl-table {',
    '  width: 100%;',
    '  border-collapse: collapse;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '.cl-table th,',
    '.cl-table td {',
    '  padding: var(--cl-space-2) var(--cl-space-3);',
    '  text-align: left;',
    '  border-block-end: 1px solid var(--cl-border-muted);',
    '}',
    '.cl-table thead th {',
    '  background: var(--cl-surface-raised);',
    '  color: var(--cl-text-muted);',
    '  font-family: var(--cl-font-display);',
    '  font-size: var(--cl-font-size-xs);',
    '  font-weight: var(--cl-weight-semibold);',
    '  text-transform: uppercase;',
    '  letter-spacing: var(--cl-tracking-wider);',
    '  white-space: nowrap;',
    '}',
    '/* Numeric columns read right-aligned against the figure above them. */',
    '.cl-table__num { text-align: right; }',
    '.cl-table tbody tr:last-child th,',
    '.cl-table tbody tr:last-child td { border-block-end: none; }',
    '',
    '/* A wide table scrolls inside its own box; the page never scrolls sideways. */',
    '.cl-table-scroll {',
    '  overflow-x: auto;',
    '  max-width: 100%;',
    '}',
    '',
    /*
     * Filter and navigation pills. Each option is its own bounded control with
     * real spacing — the alternative is four bare anchors rendering as one
     * run-on string.
     */
    '.cl-pill-group {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: var(--cl-space-2);',
    '  list-style: none;',
    '  margin: 0;',
    '  padding: 0;',
    '}',
    '.cl-pill {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--cl-space-1);',
    '  min-height: var(--cl-touch-target);',
    '  padding: var(--cl-space-1) var(--cl-space-3);',
    '  border: 1px solid var(--cl-border-muted);',
    '  background: var(--cl-surface-raised);',
    '  color: var(--cl-text-primary);',
    '  font-family: var(--cl-font-body);',
    '  font-size: var(--cl-font-size-sm);',
    '  font-weight: var(--cl-weight-semibold);',
    '  text-decoration: none;',
    '  cursor: pointer;',
    '}',
    '.cl-pill:hover { background: var(--cl-surface-hover); }',
    /* State is carried by fill *and* border, never by color alone. */
    '.cl-pill--active,',
    '.cl-pill[aria-current] {',
    '  background: var(--cl-state-live);',
    '  border-color: var(--cl-state-live);',
    '  color: var(--cl-surface-base);',
    '}',
    '',
    '.cl-inline-alert {',
    '  display: flex;',
    '  gap: var(--cl-space-2);',
    '  padding: var(--cl-space-3);',
    '  border-left: var(--cl-space-1) solid var(--cl-state-upcoming);',
    '  background: var(--cl-surface-raised);',
    '}',
    '',
    '/* An alert is its accent *and* its words: the variant colours the rail, the text says what happened. */',
    '.cl-inline-alert--destructive { border-left-color: var(--cl-state-destructive); }',
    // `success` completes the set the Alert atom exposes. Until it existed, 65
    // of 68 inline alerts declared no tone at all, so an error, a success
    // confirmation and a loading message all drew the same rail — the class was
    // doing three jobs and looking identical for each.
    '.cl-inline-alert--success { border-left-color: var(--cl-state-positive); }',
    '.cl-inline-alert--live { border-left-color: var(--cl-state-live); }',
    // Only where an alert carries more than one line. The base rule stays a
    // row: BroadcastStatusPanel and the public surfaces already lay their
    // single-line alerts out along it.
    '.cl-inline-alert--stacked { flex-direction: column; }',
    // Opt-in, never automatic: a component does not set its own external
    // margin, but a caller placing an alert after a form step needs the same
    // gap every time, and an inline `marginTop` literal at each site is what
    // this replaces.
    '.cl-inline-alert--spaced { margin-block-start: var(--cl-space-4); }',
    '.cl-inline-alert__title { margin: 0; font-weight: var(--cl-weight-bold); }',
    '.cl-inline-alert__body { margin: 0; color: var(--cl-text-secondary); font-size: var(--cl-font-size-sm); }',
    // Pushed to the end of the alert's own row rather than carrying a margin of
    // its own — the same rule the entity-card footer uses for its destructive
    // action, and for the same reason: spacing belongs to the container.
    '.cl-inline-alert__dismiss { margin-inline-start: auto; align-self: start; background: none; border: 0; color: inherit; cursor: pointer; padding: 0 var(--cl-space-1); }',
    // A card's content is a grid that owns its own spacing, so an alert placed
    // in it brings no paragraph margin of its own.
    '.cl-card__content > .cl-inline-alert { margin: 0; }',
    '',
    "/* An unauthenticated screen's form: one column, the fields evenly spaced. */",
    '.cl-auth-form { display: grid; gap: var(--cl-space-4); }',
    '',
    '/* Summary tiles are a row of peers, not a stack: one column below the md breakpoint, three above it. */',
    '.cl-stat-grid {',
    '  display: grid;',
    '  grid-template-columns: 1fr;',
    '  gap: var(--cl-space-4);',
    '  min-width: 0;',
    '}',
    '',
    '.cl-stat-grid > * { min-width: 0; }',
    '',
    `@media (min-width: ${BREAKPOINTS.md}) {`,
    '  .cl-stat-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }',
    '}',
    '',
    '.cl-stat-tile {',
    '  background: var(--cl-surface-raised);',
    '  padding: var(--cl-space-4);',
    '}',
    '',
    '.cl-stat-tile__value {',
    '  font-family: var(--cl-font-display);',
    '  font-weight: var(--cl-weight-bold);',
    '  /* Scores that shift width as they change are scores nobody can read. */',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '',
    '/* Text an assistive technology must read but the layout must not show — a state word behind an icon, most often. */',
    '.cl-visually-hidden {',
    '  position: absolute;',
    '  width: 1px;',
    '  height: 1px;',
    '  margin: -1px;',
    '  padding: 0;',
    '  overflow: hidden;',
    '  clip-path: inset(50%);',
    '  white-space: nowrap;',
    '  border: 0;',
    '}',
    '',
    /*
     * A link's colour, for every surface.
     *
     * This lived as `:global(a)` inside `PublicLayout.astro`, so only the public
     * pages ever loaded it: every link in the operator panel rendered in the
     * browser's default blue, against a dark panel, in production. A base
     * element treatment belongs with the tokens, where every surface that loads
     * the stylesheet gets it.
     */
    'a { color: var(--cl-state-live); }',
    '',
    /*
     * Headings use the display face.
     *
     * Fourteen component classes reach for `--cl-font-display` deliberately,
     * but nothing gave a bare `<h1>`-`<h6>` a family, so a page heading rendered
     * in the body face — the condensed identity the product shows off appeared
     * only where a component happened to ask for it.
     *
     * Family and tracking only: whether a given heading is uppercase is the
     * component's or the page's call, and several already decide it.
     */
    'h1, h2, h3, h4, h5, h6 { font-family: var(--cl-font-display); letter-spacing: var(--cl-tracking-wide); }',
    '',
    /*
     * An alert's paragraphs carry no margin of their own — the alert is already
     * a flex container with its own gap. Also formerly trapped in the public
     * layout, which is why a block-form alert spaced differently depending on
     * which surface rendered it.
     */
    '.cl-inline-alert p { margin: 0; }',
    '',
    '.cl-focusable:focus-visible {',
    '  outline: none;',
    `  box-shadow: 0 0 0 ${FOCUS_RING.innerWidth} var(--cl-surface-base),`,
    `    0 0 0 ${FOCUS_RING.outerWidth} var(--cl-focus-ring);`,
    '}',
    '',
    "/* The matches-view card (openspec 0172) — shared by MatchCard.tsx on both public-web and control-web, so it lives here rather than in either surface's own page-scoped styles. */",
    '.cl-match-card { display: grid; gap: var(--cl-space-3); min-width: 0; }',
    // The state badge and the clock sit on one line until they cannot: at the
    // 188px reference width a longer translation of the state — `IN DIRETTA`
    // for `LIVE` — plus a running clock exceeds the card, so the pair wraps
    // rather than widening the card past the viewport.
    '.cl-match-card__header { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: var(--cl-space-3); min-width: 0; }',
    '.cl-match-card__clock { font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); color: var(--cl-state-live); font-variant-numeric: tabular-nums; }',
    // A grid of match cards, promoted out of `MatchCardGrid.astro`'s scoped
    // style so the React surfaces can compose it too. While it lived there,
    // `LiveMatchHero` had no grid to reach and stacked one full-width card per
    // row, wasting most of a 1440px viewport.
    //
    // `min(100%, 280px)` rather than a bare 280px floor: a hard minimum wider
    // than the viewport makes the page itself scroll sideways at the 188px
    // reference width. The local copy had that latent bug and never hit it,
    // because it was only ever rendered inside a page that constrained it.
    '.cl-match-card-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 280px), 1fr)); gap: var(--cl-space-3); list-style: none; padding: 0; margin: 0; }',
    '.cl-match-card__sides { display: grid; gap: var(--cl-space-2); margin: 0; padding: 0; list-style: none; }',
    '.cl-match-card__side { display: flex; align-items: center; gap: var(--cl-space-2); min-width: 0; }',
    '.cl-match-card__side .cl-badge--rank { font-family: var(--cl-font-mono); font-variant-numeric: tabular-nums; flex: 0 0 auto; }',
    ".cl-match-card__side > span[data-testid='entrant-name'] { flex: 1 1 auto; font-family: var(--cl-font-display); font-weight: var(--cl-weight-medium); font-size: var(--cl-font-size-lg); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    '.cl-match-card__side .cl-stat-tile__value { flex: 0 0 auto; font-size: var(--cl-font-size-2xl); background: none; padding: 0; }',
    '.cl-match-card__scope, .cl-match-card__venue, .cl-match-card__event { margin: 0; color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; letter-spacing: var(--cl-tracking-wide); }',
    '.cl-match-card__event { color: var(--cl-text-secondary); }',
    '.cl-match-card__series { display: grid; gap: var(--cl-space-1); padding: var(--cl-space-3); background: var(--cl-surface-raised); border-left: 2px solid var(--cl-state-upcoming); }',
    '.cl-match-card__series .cl-series__score { margin: 0; font-family: var(--cl-font-mono); font-size: var(--cl-font-size-lg); }',
    '.cl-match-card__series .cl-series__pending, .cl-match-card__series .cl-series__decided, .cl-match-card__series .cl-series__aggregate { margin: 0; color: var(--cl-text-secondary); font-size: var(--cl-font-size-sm); }',
    '.cl-match-card__deciding-factor { margin: 0; padding: var(--cl-space-2) var(--cl-space-3); background: var(--cl-surface-raised); border-left: 2px solid var(--cl-focus-ring); color: var(--cl-text-secondary); font-size: var(--cl-font-size-sm); }',
    '.cl-match-card__trace { border-top: 1px solid var(--cl-border-muted); padding-top: var(--cl-space-2); }',
    '.cl-match-card__trace > summary { cursor: pointer; color: var(--cl-focus-ring); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); text-transform: uppercase; }',
    '.cl-match-card__trace-lines { margin: var(--cl-space-2) 0 0; padding-left: var(--cl-space-4); color: var(--cl-text-muted); font-family: var(--cl-font-mono); font-size: var(--cl-font-size-xs); }',
    // `min(100%, 280px)` rather than a bare floor: a hard minimum wider than
    // the viewport makes the page scroll sideways. Flagged when the entity-card
    // grid got the same treatment and left alone because this route was not in
    // the responsive gate's list — which only ever meant nobody was looking.
    // `auto-fill`, matching `.cl-match-card-grid`. With `auto-fit` the empty
    // tracks collapse, so a tournament with one match rendered a single card
    // 1408px wide on the matches view while the same card sat at 343px on the
    // live page — two grids for one kind of card, disagreeing about what a card
    // is. A match card has a size; a row with one of them is a row with a gap.
    '.cl-matches-view__grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 280px), 1fr)); gap: var(--cl-space-4); }',
  ].join('\n');
}

/** One state-keyed rule block per form-control atom. */
function formControls(): string {
  const groups: readonly [string, Record<FormControlState, FormControlTokenSet>][] = [
    ['input', INPUT_TOKENS],
    ['select', SELECT_TOKENS],
    ['textarea', TEXTAREA_TOKENS],
    ['checkbox', CHECKBOX_TOKENS],
  ];

  return groups
    .map(([atom, states]) =>
      (Object.entries(states) as [FormControlState, FormControlTokenSet][])
        .map(([state, tokens]) =>
          [
            `.cl-${atom}--${state} {`,
            `  background: var(--cl-${tokens.background});`,
            `  color: var(--cl-${tokens.text});`,
            `  border-color: var(--cl-${tokens.border});`,
            '}',
          ].join('\n'),
        )
        .join('\n'),
    )
    .join('\n\n');
}

/** The `Modal`/`Dialog` organism's overlay and content-panel tokens. */
function dialog(): string {
  return [
    '.cl-dialog-backdrop {',
    `  background: var(--cl-${DIALOG_TOKENS.backdrop});`,
    '}',
    '',
    '.cl-dialog-surface {',
    `  background: var(--cl-${DIALOG_TOKENS.surface});`,
    `  border: 1px solid var(--cl-${DIALOG_TOKENS.border});`,
    `  box-shadow: ${DIALOG_TOKENS.elevation};`,
    '}',
  ].join('\n');
}

/**
 * Control-web's denser spacing composition, scoped to `[data-density="control"]`
 * so the exact same atoms render tighter there than on the marketing surfaces —
 * a composition choice, not a second component tree (design.md Decision 4).
 */
function density(): string {
  return [
    '[data-density="control"] {',
    ...Object.entries(CONTROL_DENSITY_SPACING).map(
      ([name, value]) => `  --cl-density-${name}: ${value};`,
    ),
    '}',
  ].join('\n');
}
