import {
  COLOR_PRIMITIVES,
  FONT_WEIGHTS,
  MOTION,
  RADIUS,
  SPACING,
  TYPOGRAPHY,
} from '../primitives.js';
import { SEMANTIC_COLORS } from '../semantic.js';

/**
 * The same values as a Tailwind theme (0019), for the React control app.
 *
 * Generated from one source rather than hand-kept alongside the CSS, because
 * hand-duplication is precisely how a "live" cyan ends up two shades apart on
 * the public page and the operator console.
 *
 * The semantic tokens point at the CSS custom properties instead of copying the
 * hex, so a theme override at runtime moves both surfaces at once.
 */

export interface TailwindTheme {
  readonly colors: Record<string, string>;
  readonly fontFamily: Record<string, string[]>;
  readonly fontWeight: Record<string, string>;
  readonly spacing: Record<string, string>;
  readonly borderRadius: Record<string, string>;
  readonly transitionDuration: Record<string, string>;
}

export function generateTailwindTheme(): TailwindTheme {
  const colors: Record<string, string> = {};
  for (const [name, value] of Object.entries(COLOR_PRIMITIVES)) colors[`cl-${name}`] = value;
  for (const name of Object.keys(SEMANTIC_COLORS)) colors[name] = `var(--cl-${name})`;

  return {
    colors,
    fontFamily: {
      display: split(TYPOGRAPHY.display),
      body: split(TYPOGRAPHY.body),
      mono: split(TYPOGRAPHY.mono),
    },
    fontWeight: { ...FONT_WEIGHTS },
    spacing: Object.fromEntries(
      Object.entries(SPACING).map(([name, value]) => [`cl-${name}`, value]),
    ),
    borderRadius: Object.fromEntries(
      Object.entries(RADIUS).map(([name, value]) => [`cl-${name}`, value]),
    ),
    transitionDuration: {
      'cl-fast': MOTION.fast,
      'cl-base': MOTION.base,
      'cl-slow': MOTION.slow,
    },
  };
}

export function generateTailwindModule(): string {
  return [
    '// Generated by @copalibre/design-tokens (0019). Do not edit by hand.',
    `export const copalibreTheme = ${JSON.stringify(generateTailwindTheme(), null, 2)};`,
    '',
  ].join('\n');
}

function split(stack: string): string[] {
  return stack.split(',').map((family) => family.trim().replace(/^'|'$/g, ''));
}
