import { generateKeyPairSync, createPublicKey, randomBytes } from 'node:crypto';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { getAsset, isSea } from 'node:sea';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCopalibreVersion } from './banner.js';
import { writeInstallationMarker, type InstallationMarker } from './installation-marker.js';

export function generateRandomSecret(bytes = 32): string {
  return randomBytes(bytes).toString('hex');
}

export const LOCAL_DEFAULTS = {
  COPALIBRE_PORT: '8080',
  COPALIBRE_APP_URL: 'http://localhost:8080',
  COPALIBRE_API_URL: 'http://localhost:8080',
  COPALIBRE_IMAGE: 'ghcr.io/sebasoft/copalibre:1.2.1',
  COPALIBRE_WEB_IMAGE: 'ghcr.io/sebasoft/copalibre-web:1.2.1',
  POSTGRES_USER: 'copalibre',
  POSTGRES_PASSWORD: 'copalibre_dev_password',
  POSTGRES_DB: 'copalibre',
  COPALIBRE_BOOTSTRAP_TOKEN: 'copalibre_bootstrap_token_secret',
  COPALIBRE_JWKS_URI: 'http://api:3001/.well-known/jwks.json',
  COPALIBRE_JWT_ISSUER: 'http://localhost:8080',
  COPALIBRE_JWT_AUDIENCE: 'copalibre',
  COPALIBRE_OIDC_CLIENT_ID: 'copalibre-local',
  COPALIBRE_EMAIL_PROVIDER: 'smtp',
  COPALIBRE_EMAIL_FROM: 'noreply@copalibre.local',
  COPALIBRE_SMTP_URL: 'smtp://host.docker.internal:1025',
  GARAGE_RPC_SECRET: 'copalibre_garage_rpc_secret_change_me',
  COPALIBRE_MODULE_SOURCE_ALLOWLIST: 'file:///var/lib/copalibre/modules',
  COPALIBRE_DATA_DIR: './data',
  COPALIBRE_API_PORT: '3001',
  COPALIBRE_EVENTS_PORT: '3002',
  COPALIBRE_WORKER_PORT: '3003',
  COPALIBRE_SCHEDULER_PORT: '3004',
} as const;

export const REQUIRED_SECRETS = [
  'POSTGRES_PASSWORD',
  'COPALIBRE_BOOTSTRAP_TOKEN',
  'COPALIBRE_JWKS_URI',
  'COPALIBRE_JWT_ISSUER',
  'COPALIBRE_JWT_AUDIENCE',
  'COPALIBRE_OIDC_CLIENT_ID',
  'COPALIBRE_EMAIL_PROVIDER',
  'COPALIBRE_EMAIL_FROM',
  'Selected email provider credential',
] as const;

export function generateRsaKeypair(): {
  readonly privateKeyPem: string;
  readonly jwksJson: string;
} {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: {
      type: 'spki',
      format: 'pem',
    },
    privateKeyEncoding: {
      type: 'pkcs8',
      format: 'pem',
    },
  });

  const jwk = createPublicKey(publicKey).export({ format: 'jwk' });
  const keyId = 'copalibre-local-key-1';
  const jwks = {
    keys: [
      {
        ...jwk,
        kid: keyId,
        use: 'sig',
        alg: 'RS256',
      },
    ],
  };

  return {
    privateKeyPem: privateKey,
    jwksJson: JSON.stringify(jwks, null, 2),
  };
}

/**
 * The `.env` body `init` writes — pure, so the build-time asset generator
 * (`scripts/build-assets.mjs`, producing `.env.example`) can reuse the exact
 * same content without duplicating the format.
 */
export function localDefaultsEnvFile(overrides: Record<string, string> = {}): string {
  const merged = {
    ...LOCAL_DEFAULTS,
    GARAGE_RPC_SECRET: overrides.GARAGE_RPC_SECRET ?? generateRandomSecret(32),
    ...overrides,
  };
  return [
    '# Generated by copalibre init. Add secrets outside version control.',
    ...Object.entries(merged).map(([key, value]) => `${key}=${value}`),
    '',
  ].join('\n');
}

export async function writeLocalDefaults(
  file: string,
  extraLines: readonly string[] = [],
  overrides: Record<string, string> = {},
): Promise<void> {
  await mkdir(dirname(file), { recursive: true });
  const base = localDefaultsEnvFile(overrides);
  const body =
    extraLines.length === 0 ? base : base + extraLines.map((line) => `${line}\n`).join('');
  await writeFile(file, body, { encoding: 'utf8', flag: 'wx', mode: 0o600 });
  await chmod(file, 0o600);
}

export async function scaffoldLocalModules(
  cwd: string,
  disciplines: readonly string[] = ['football', 'tennis'],
): Promise<{
  readonly modulesDir: string;
  readonly disciplinesDir: string;
  readonly profilesDir: string;
  readonly readmeFile: string;
  readonly provisionedDisciplines: readonly string[];
}> {
  const modulesDir = join(cwd, 'modules');
  const disciplinesDir = join(modulesDir, 'disciplines');
  const profilesDir = join(modulesDir, 'profiles');
  await mkdir(disciplinesDir, { recursive: true });
  await mkdir(profilesDir, { recursive: true });

  const readmeFile = join(modulesDir, 'README.md');
  const readmeContent = `# CopaLibre Local Modules Directory

This directory is mounted read-only into CopaLibre containers at \`/var/lib/copalibre/modules\`.

## Directory Layout
- \`disciplines/\`: Custom or offline sport disciplines. Each discipline folder should contain \`manifest.json\`, \`artifact.json\`, rules, and assets.
- \`profiles/\`: Custom tournament profiles (formats, phases, advancing rules).

## Provisioned Starter Disciplines
${disciplines.map((d) => `- ${d}`).join('\n')}

To install an offline discipline from this directory, run:
\`copalibre module add --source file:///var/lib/copalibre/modules <alias>\`
`;
  await writeFile(readmeFile, readmeContent, 'utf8');

  for (const alias of disciplines) {
    const starterDisciplineDir = join(disciplinesDir, alias);
    await mkdir(starterDisciplineDir, { recursive: true });
    const manifestPath = join(starterDisciplineDir, 'manifest.json');
    if (!existsSync(manifestPath)) {
      await writeFile(
        manifestPath,
        JSON.stringify(
          {
            alias,
            kind: 'discipline',
            name: alias.charAt(0).toUpperCase() + alias.slice(1).replace('-', ' '),
            version: '1.0.0',
            requiresCopalibre: '>=1.0.0',
          },
          null,
          2,
        ),
        'utf8',
      );
    }
  }

  return {
    modulesDir,
    disciplinesDir,
    profilesDir,
    readmeFile,
    provisionedDisciplines: disciplines,
  };
}

export function formatRequiredSecrets(): string {
  return REQUIRED_SECRETS.map((name) => `- ${name}`).join('\n');
}

/**
 * `apps/copalibre`'s own embedded copies of the compose files —
 * `scripts/build-assets.mjs` copies them here at build time, alongside
 * `dist/init.js`, so the CLI has something local to read without depending
 * on a checkout when running as `node dist/main.js`. A packaged standalone
 * binary never resolves this path at all (`import.meta.url` isn't meaningful
 * once bundled to CJS) — `readAsset` reads its embedded SEA asset instead,
 * so this is computed lazily, only on the non-`isSea()` branch.
 */
function defaultAssetsDir(): string {
  return join(dirname(fileURLToPath(import.meta.url)), 'assets');
}

export interface ReadAssetDependencies {
  readonly isSea?: () => boolean;
  readonly getAsset?: (key: string, encoding: string) => string;
}

/**
 * Reads one of the embedded compose assets: `sea.getAsset()` when running as
 * a packaged single-executable binary (the asset is bundled into the binary
 * itself, `build-binary.mjs`'s SEA config), otherwise a plain read from
 * `assetsDir` — the `node dist/main.js` and test cases, where `assetsDir`
 * always has these files on disk. Exported so both branches are directly
 * unit-testable without mocking the `node:sea` module.
 */
export async function readAsset(
  name: string,
  assetsDir?: string,
  dependencies: ReadAssetDependencies = {},
): Promise<string> {
  const isSeaFunction = dependencies.isSea ?? isSea;
  const getAssetFunction = dependencies.getAsset ?? getAsset;
  if (isSeaFunction()) return getAssetFunction(name, 'utf8');
  return readFile(join(assetsDir ?? defaultAssetsDir(), name), 'utf8');
}

export interface WriteInstallationAssetsOptions {
  readonly moduleDev?: boolean;
  /**
   * Overrides where the embedded compose files are read from (ignored when
   * running as a packaged binary, which always reads its embedded SEA asset)
   * — real callers never set this (defaults to the directory
   * `scripts/build-assets.mjs` populates); tests do, since a pure unit-test
   * run against `src/init.ts` directly has no built `dist/assets/` to read
   * from.
   */
  readonly assetsDir?: string;
  readonly proxy?: string;
  readonly appUrl?: string;
  readonly apiUrl?: string;
  readonly starterDisciplines?: readonly string[];
}

export interface WriteInstallationAssetsResult {
  readonly directory: string;
  readonly composeFile: string;
  readonly envFile: string;
  readonly privateKeyFile: string;
  readonly jwksFile: string;
  readonly moduleDevFile?: string;
  readonly proxyConfigFile?: string;
  readonly marker: InstallationMarker;
}

/**
 * `copalibre init`'s real work: writes a complete, runnable installation
 * into `cwd` with no source checkout required — the compose file, `.env`,
 * RSA keypair, gateway Caddyfile, and (opt-in) the module-dev override,
 * plus the marker every later command auto-detects.
 */
export async function writeInstallationAssets(
  cwd: string,
  options: WriteInstallationAssetsOptions = {},
): Promise<WriteInstallationAssetsResult> {
  const composeTarget = join(cwd, 'docker-compose.yml');
  const envTarget = join(cwd, '.env');
  const privateKeyTarget = join(cwd, 'jwt-private.pem');
  const jwksTarget = join(cwd, 'jwks.json');
  const gatewayTarget = join(cwd, 'deploy', 'gateway', 'Caddyfile');
  const moduleDevTarget = join(cwd, 'docker-compose.module-dev.yml');
  const markerTarget = join(cwd, '.copalibre', 'installation.json');

  const targets = [
    composeTarget,
    envTarget,
    privateKeyTarget,
    jwksTarget,
    markerTarget,
    ...(options.moduleDev ? [moduleDevTarget] : []),
  ];
  const conflicting = targets.find((target) => existsSync(target));
  if (conflicting) {
    throw new Error(
      `"${conflicting}" already exists — this directory may already hold a CopaLibre installation. ` +
        'Run "copalibre init" in an empty directory, or remove the conflicting file first.',
    );
  }

  await mkdir(cwd, { recursive: true });
  await writeFile(composeTarget, await readAsset('docker-compose.yml', options.assetsDir), 'utf8');

  // Generate and write RSA keys for local token signing directly alongside .env
  const { privateKeyPem, jwksJson } = generateRsaKeypair();
  await writeFile(privateKeyTarget, privateKeyPem, { encoding: 'utf8', mode: 0o600 });
  await chmod(privateKeyTarget, 0o600);
  await writeFile(jwksTarget, jwksJson, { encoding: 'utf8', mode: 0o644 });

  // Write gateway Caddyfile
  await mkdir(dirname(gatewayTarget), { recursive: true });
  let gatewayCaddyContent: string;
  try {
    gatewayCaddyContent = await readAsset('Caddyfile', options.assetsDir);
  } catch {
    gatewayCaddyContent = `:80 {
\t# Realtime SSE stream
\t@events path /events /events/*
\thandle @events {
\t\treverse_proxy events:3002 {
\t\t\tflush_interval -1
\t\t}
\t}

\t# Microservice API endpoints (incluye rutas base y subrutas)
\t@api path /api /api/* /auth /auth/* /organizations /organizations/* /objects /objects/* /admin /admin/* /installation /installation/* /.well-known /.well-known/* /disciplines /disciplines/* /tournament-profiles /tournament-profiles/*
\thandle @api {
\t\treverse_proxy api:3001
\t}

\t# Web frontend
\thandle {
\t\treverse_proxy web:4321
\t}
}
`;
  }
  await writeFile(gatewayTarget, gatewayCaddyContent, 'utf8');

  if (options.moduleDev) {
    await writeFile(
      moduleDevTarget,
      await readAsset('docker-compose.module-dev.yml', options.assetsDir),
      'utf8',
    );
    await mkdir(join(cwd, 'modules-dev'), { recursive: true });
  }

  const overrides: Record<string, string> = {};
  if (options.appUrl) {
    overrides.COPALIBRE_APP_URL = options.appUrl;
    overrides.COPALIBRE_API_URL = options.apiUrl ?? options.appUrl;
    overrides.COPALIBRE_JWT_ISSUER = options.appUrl;
  } else if (options.apiUrl) {
    overrides.COPALIBRE_API_URL = options.apiUrl;
  }

  const extraLines = options.moduleDev
    ? ['COMPOSE_FILE=docker-compose.yml:docker-compose.module-dev.yml']
    : [];
  await writeLocalDefaults(envTarget, extraLines, overrides);

  // Scaffold local ./modules hierarchy and starter disciplines
  await scaffoldLocalModules(cwd, options.starterDisciplines ?? ['football', 'tennis']);

  // Handle proxy configuration export
  let proxyConfigFile: string | undefined;
  if (options.proxy === 'nginx') {
    proxyConfigFile = join(cwd, 'copalibre-nginx.conf');
    let proxyContent: string;
    try {
      proxyContent = await readAsset('copalibre.conf', options.assetsDir);
    } catch {
      proxyContent = `# CopaLibre Reverse Proxy Configuration for Nginx
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 80;
  listen [::]:80;
  server_name play.example.com;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Port $server_port;

  client_max_body_size 100M;
  proxy_request_buffering off;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;

  location /events/ {
    proxy_pass http://127.0.0.1:8080/events/;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_cache off;
    chunked_transfer_encoding off;
    proxy_set_header Connection '';
    add_header X-Accel-Buffering "no" always;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
  }

  location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }
}
`;
    }
    if (options.appUrl) {
      try {
        const hostname = new URL(options.appUrl).hostname;
        if (hostname && hostname !== 'localhost' && hostname !== '127.0.0.1') {
          proxyContent = proxyContent.replace(
            /server_name\s+play\.example\.com;/,
            `server_name ${hostname};`,
          );
        }
      } catch {
        // preserve default server_name
      }
    }
    await writeFile(proxyConfigFile, proxyContent, 'utf8');
  }

  const marker = await writeInstallationMarker(cwd, readCopalibreVersion());

  return {
    directory: cwd,
    composeFile: composeTarget,
    envFile: envTarget,
    privateKeyFile: privateKeyTarget,
    jwksFile: jwksTarget,
    ...(options.moduleDev ? { moduleDevFile: moduleDevTarget } : {}),
    ...(proxyConfigFile ? { proxyConfigFile } : {}),
    marker,
  };
}
