import { generateKeyPairSync, createPublicKey } from 'node:crypto';
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { getAsset, isSea } from 'node:sea';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCopalibreVersion } from './banner.js';
import { writeInstallationMarker, type InstallationMarker } from './installation-marker.js';

export const LOCAL_DEFAULTS = {
  COPALIBRE_PORT: '8080',
  COPALIBRE_APP_URL: 'http://localhost:8080',
  COPALIBRE_API_URL: 'http://localhost:8080',
  COPALIBRE_IMAGE: 'ghcr.io/sebasoft/copalibre:1.0.6',
  COPALIBRE_WEB_IMAGE: 'ghcr.io/sebasoft/copalibre-web:1.0.6',
  POSTGRES_USER: 'copalibre',
  POSTGRES_PASSWORD: 'copalibre_dev_password',
  POSTGRES_DB: 'copalibre',
  COPALIBRE_BOOTSTRAP_TOKEN: 'copalibre_bootstrap_token_secret',
  COPALIBRE_JWKS_URI: 'http://api:3001/.well-known/jwks.json',
  COPALIBRE_JWT_ISSUER: 'http://localhost:8080',
  COPALIBRE_JWT_AUDIENCE: 'copalibre',
  COPALIBRE_OIDC_CLIENT_ID: 'copalibre-local',
  COPALIBRE_EMAIL_PROVIDER: 'smtp',
  COPALIBRE_EMAIL_FROM: 'noreply@copalibre.local',
  COPALIBRE_SMTP_URL: 'smtp://host.docker.internal:1025',
  COPALIBRE_DATA_DIR: './data',
  COPALIBRE_API_PORT: '3001',
  COPALIBRE_EVENTS_PORT: '3002',
  COPALIBRE_WORKER_PORT: '3003',
  COPALIBRE_SCHEDULER_PORT: '3004',
} as const;

export const REQUIRED_SECRETS = [
  'POSTGRES_PASSWORD',
  'COPALIBRE_BOOTSTRAP_TOKEN',
  'COPALIBRE_JWKS_URI',
  'COPALIBRE_JWT_ISSUER',
  'COPALIBRE_JWT_AUDIENCE',
  'COPALIBRE_OIDC_CLIENT_ID',
  'COPALIBRE_EMAIL_PROVIDER',
  'COPALIBRE_EMAIL_FROM',
  'Selected email provider credential',
] as const;

export function generateRsaKeypair(): { readonly privateKeyPem: string; readonly jwksJson: string } {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: {
      type: 'spki',
      format: 'pem',
    },
    privateKeyEncoding: {
      type: 'pkcs8',
      format: 'pem',
    },
  });

  const jwk = createPublicKey(publicKey).export({ format: 'jwk' });
  const keyId = 'copalibre-local-key-1';
  const jwks = {
    keys: [
      {
        ...jwk,
        kid: keyId,
        use: 'sig',
        alg: 'RS256',
      },
    ],
  };

  return {
    privateKeyPem: privateKey,
    jwksJson: JSON.stringify(jwks, null, 2),
  };
}

/**
 * The `.env` body `init` writes — pure, so the build-time asset generator
 * (`scripts/build-assets.mjs`, producing `.env.example`) can reuse the exact
 * same content without duplicating the format.
 */
export function localDefaultsEnvFile(): string {
  return [
    '# Generated by copalibre init. Add secrets outside version control.',
    ...Object.entries(LOCAL_DEFAULTS).map(([key, value]) => `${key}=${value}`),
    '',
  ].join('\n');
}

export async function writeLocalDefaults(
  file: string,
  extraLines: readonly string[] = [],
): Promise<void> {
  await mkdir(dirname(file), { recursive: true });
  const body =
    extraLines.length === 0
      ? localDefaultsEnvFile()
      : localDefaultsEnvFile() + extraLines.map((line) => `${line}\n`).join('');
  await writeFile(file, body, { encoding: 'utf8', flag: 'wx', mode: 0o600 });
  await chmod(file, 0o600);
}

export function formatRequiredSecrets(): string {
  return REQUIRED_SECRETS.map((name) => `- ${name}`).join('\n');
}

/**
 * `apps/copalibre`'s own embedded copies of the compose files —
 * `scripts/build-assets.mjs` copies them here at build time, alongside
 * `dist/init.js`, so the CLI has something local to read without depending
 * on a checkout when running as `node dist/main.js`. A packaged standalone
 * binary never resolves this path at all (`import.meta.url` isn't meaningful
 * once bundled to CJS) — `readAsset` reads its embedded SEA asset instead,
 * so this is computed lazily, only on the non-`isSea()` branch.
 */
function defaultAssetsDir(): string {
  return join(dirname(fileURLToPath(import.meta.url)), 'assets');
}

export interface ReadAssetDependencies {
  readonly isSea?: () => boolean;
  readonly getAsset?: (key: string, encoding: string) => string;
}

/**
 * Reads one of the embedded compose assets: `sea.getAsset()` when running as
 * a packaged single-executable binary (the asset is bundled into the binary
 * itself, `build-binary.mjs`'s SEA config), otherwise a plain read from
 * `assetsDir` — the `node dist/main.js` and test cases, where `assetsDir`
 * always has these files on disk. Exported so both branches are directly
 * unit-testable without mocking the `node:sea` module.
 */
export async function readAsset(
  name: string,
  assetsDir?: string,
  dependencies: ReadAssetDependencies = {},
): Promise<string> {
  const isSeaFunction = dependencies.isSea ?? isSea;
  const getAssetFunction = dependencies.getAsset ?? getAsset;
  if (isSeaFunction()) return getAssetFunction(name, 'utf8');
  return readFile(join(assetsDir ?? defaultAssetsDir(), name), 'utf8');
}

export interface WriteInstallationAssetsOptions {
  readonly moduleDev?: boolean;
  /**
   * Overrides where the embedded compose files are read from (ignored when
   * running as a packaged binary, which always reads its embedded SEA asset)
   * — real callers never set this (defaults to the directory
   * `scripts/build-assets.mjs` populates); tests do, since a pure unit-test
   * run against `src/init.ts` directly has no built `dist/assets/` to read
   * from.
   */
  readonly assetsDir?: string;
}

export interface WriteInstallationAssetsResult {
  readonly directory: string;
  readonly composeFile: string;
  readonly envFile: string;
  readonly privateKeyFile: string;
  readonly jwksFile: string;
  readonly moduleDevFile?: string;
  readonly marker: InstallationMarker;
}

/**
 * `copalibre init`'s real work: writes a complete, runnable installation
 * into `cwd` with no source checkout required — the compose file, `.env`,
 * RSA keypair, gateway Caddyfile, and (opt-in) the module-dev override,
 * plus the marker every later command auto-detects.
 */
export async function writeInstallationAssets(
  cwd: string,
  options: WriteInstallationAssetsOptions = {},
): Promise<WriteInstallationAssetsResult> {
  const composeTarget = join(cwd, 'docker-compose.yml');
  const envTarget = join(cwd, '.env');
  const privateKeyTarget = join(cwd, 'jwt-private.pem');
  const jwksTarget = join(cwd, 'jwks.json');
  const gatewayTarget = join(cwd, 'deploy', 'gateway', 'Caddyfile');
  const moduleDevTarget = join(cwd, 'docker-compose.module-dev.yml');
  const markerTarget = join(cwd, '.copalibre', 'installation.json');

  const targets = [
    composeTarget,
    envTarget,
    privateKeyTarget,
    jwksTarget,
    markerTarget,
    ...(options.moduleDev ? [moduleDevTarget] : []),
  ];
  const conflicting = targets.find((target) => existsSync(target));
  if (conflicting) {
    throw new Error(
      `"${conflicting}" already exists — this directory may already hold a CopaLibre installation. ` +
        'Run "copalibre init" in an empty directory, or remove the conflicting file first.',
    );
  }

  await mkdir(cwd, { recursive: true });
  await writeFile(composeTarget, await readAsset('docker-compose.yml', options.assetsDir), 'utf8');

  // Generate and write RSA keys for local token signing directly alongside .env
  const { privateKeyPem, jwksJson } = generateRsaKeypair();
  await writeFile(privateKeyTarget, privateKeyPem, { encoding: 'utf8', mode: 0o600 });
  await chmod(privateKeyTarget, 0o600);
  await writeFile(jwksTarget, jwksJson, { encoding: 'utf8', mode: 0o644 });

  // Write gateway Caddyfile
  await mkdir(dirname(gatewayTarget), { recursive: true });
  let gatewayCaddyContent: string;
  try {
    gatewayCaddyContent = await readAsset('Caddyfile', options.assetsDir);
  } catch {
    gatewayCaddyContent = `:80 {
\thandle /api/* {
\t\treverse_proxy api:3001
\t}
\thandle /auth/* {
\t\treverse_proxy api:3001
\t}
\thandle /organizations/* {
\t\treverse_proxy api:3001
\t}
\thandle /admin/* {
\t\treverse_proxy api:3001
\t}
\thandle /installation/* {
\t\treverse_proxy api:3001
\t}
\thandle /.well-known/* {
\t\treverse_proxy api:3001
\t}
\thandle /events/* {
\t\treverse_proxy events:3002 {
\t\t\tflush_interval -1
\t\t}
\t}
\thandle {
\t\treverse_proxy web:4321
\t}
}
`;
  }
  await writeFile(gatewayTarget, gatewayCaddyContent, 'utf8');

  if (options.moduleDev) {
    await writeFile(
      moduleDevTarget,
      await readAsset('docker-compose.module-dev.yml', options.assetsDir),
      'utf8',
    );
    await mkdir(join(cwd, 'modules-dev'), { recursive: true });
  }

  const extraLines = options.moduleDev
    ? ['COMPOSE_FILE=docker-compose.yml:docker-compose.module-dev.yml']
    : [];
  await writeLocalDefaults(envTarget, extraLines);

  const marker = await writeInstallationMarker(cwd, readCopalibreVersion());

  return {
    directory: cwd,
    composeFile: composeTarget,
    envFile: envTarget,
    privateKeyFile: privateKeyTarget,
    jwksFile: jwksTarget,
    ...(options.moduleDev ? { moduleDevFile: moduleDevTarget } : {}),
    marker,
  };
}
