import { chmod, copyFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readCopalibreVersion } from './banner.js';
import { writeInstallationMarker, type InstallationMarker } from './installation-marker.js';

export const LOCAL_DEFAULTS = {
  COPALIBRE_APP_URL: 'http://localhost:4321',
  COPALIBRE_API_URL: 'http://localhost:3001',
  COPALIBRE_DATA_DIR: './data',
  COPALIBRE_API_PORT: '3001',
  COPALIBRE_EVENTS_PORT: '3002',
  COPALIBRE_WORKER_PORT: '3003',
  COPALIBRE_SCHEDULER_PORT: '3004',
} as const;

export const REQUIRED_SECRETS = [
  'POSTGRES_PASSWORD',
  'COPALIBRE_BOOTSTRAP_TOKEN',
  'COPALIBRE_JWKS_URI',
  'COPALIBRE_JWT_ISSUER',
  'COPALIBRE_JWT_AUDIENCE',
  'COPALIBRE_OIDC_CLIENT_ID',
  'COPALIBRE_EMAIL_PROVIDER',
  'COPALIBRE_EMAIL_FROM',
  'Selected email provider credential',
] as const;

/**
 * The `.env` body `init` writes — pure, so the build-time asset generator
 * (`scripts/build-assets.mjs`, producing `.env.example`, 0084) can reuse the
 * exact same content without duplicating the format.
 */
export function localDefaultsEnvFile(): string {
  return [
    '# Generated by copalibre init. Add secrets outside version control.',
    ...Object.entries(LOCAL_DEFAULTS).map(([key, value]) => `${key}=${value}`),
    '',
  ].join('\n');
}

export async function writeLocalDefaults(
  file: string,
  extraLines: readonly string[] = [],
): Promise<void> {
  await mkdir(dirname(file), { recursive: true });
  const body =
    extraLines.length === 0
      ? localDefaultsEnvFile()
      : localDefaultsEnvFile() + extraLines.map((line) => `${line}\n`).join('');
  await writeFile(file, body, { encoding: 'utf8', flag: 'wx', mode: 0o600 });
  await chmod(file, 0o600);
}

export function formatRequiredSecrets(): string {
  return REQUIRED_SECRETS.map((name) => `- ${name}`).join('\n');
}

/**
 * `apps/copalibre`'s own embedded copies of the compose files (0084) —
 * `scripts/build-assets.mjs` copies them here at build time, alongside
 * `dist/init.js`, so a packaged CLI (eventually a single binary, `0086`)
 * still has something local to read without depending on a checkout.
 */
const ASSETS_DIR = join(dirname(fileURLToPath(import.meta.url)), 'assets');

export interface WriteInstallationAssetsOptions {
  readonly moduleDev?: boolean;
  /**
   * Overrides where the embedded compose files are read from — real callers
   * never set this (defaults to `ASSETS_DIR`, populated by
   * `scripts/build-assets.mjs`); tests do, since a pure unit-test run against
   * `src/init.ts` directly has no built `dist/assets/` to read from.
   */
  readonly assetsDir?: string;
}

export interface WriteInstallationAssetsResult {
  readonly directory: string;
  readonly composeFile: string;
  readonly envFile: string;
  readonly moduleDevFile?: string;
  readonly marker: InstallationMarker;
}

/**
 * `copalibre init`'s real work (0084): writes a complete, runnable
 * installation into `cwd` with no source checkout required — the compose
 * file, `.env`, and (opt-in) the module-dev override, plus the marker every
 * later command auto-detects. Every target checked for pre-existence before
 * any write begins, so a partial pre-existing state (e.g. a stray `.env`)
 * refuses cleanly, naming exactly what conflicts, rather than writing some
 * files and leaving others alone.
 */
export async function writeInstallationAssets(
  cwd: string,
  options: WriteInstallationAssetsOptions = {},
): Promise<WriteInstallationAssetsResult> {
  const composeTarget = join(cwd, 'docker-compose.yml');
  const envTarget = join(cwd, '.env');
  const moduleDevTarget = join(cwd, 'docker-compose.module-dev.yml');
  const markerTarget = join(cwd, '.copalibre', 'installation.json');

  const targets = [
    composeTarget,
    envTarget,
    markerTarget,
    ...(options.moduleDev ? [moduleDevTarget] : []),
  ];
  const conflicting = targets.find((target) => existsSync(target));
  if (conflicting) {
    throw new Error(
      `"${conflicting}" already exists — this directory may already hold a CopaLibre installation. ` +
        'Run "copalibre init" in an empty directory, or remove the conflicting file first.',
    );
  }

  const assetsDir = options.assetsDir ?? ASSETS_DIR;
  await mkdir(cwd, { recursive: true });
  await copyFile(join(assetsDir, 'docker-compose.yml'), composeTarget);

  if (options.moduleDev) {
    await copyFile(join(assetsDir, 'docker-compose.module-dev.yml'), moduleDevTarget);
    await mkdir(join(cwd, 'modules-dev'), { recursive: true });
  }
  // Always explicit, never left to Compose's own cwd-scanning discovery —
  // `-f` flags passed by hand at invocation time would override (not merge
  // with) this, silently dropping the module-dev override, so cli-runner.ts's
  // marker-aware dispatch relies on this instead of passing `-f` itself.
  const composeFile = options.moduleDev
    ? 'docker-compose.yml:docker-compose.module-dev.yml'
    : 'docker-compose.yml';
  await writeLocalDefaults(envTarget, [`COMPOSE_FILE=${composeFile}`]);

  const marker = await writeInstallationMarker(cwd, readCopalibreVersion());

  return {
    directory: cwd,
    composeFile: composeTarget,
    envFile: envTarget,
    ...(options.moduleDev ? { moduleDevFile: moduleDevTarget } : {}),
    marker,
  };
}
