import type { DisciplineDescriptor } from '../descriptors/discipline-descriptor.js';
import { segmentThresholdEventDefinitions } from '../descriptors/segment-threshold-events.js';
import { winConditionScript } from './win-condition-scripts.js';

/**
 * Association-football descriptor builder for rules and engine tests.
 *
 * Every statistic the standings engine used to assume is declared here, which
 * is the point of the vocabulary belongs to the module, not to
 * `computeAccounting`. `played` aggregates as `count` (one per recorded
 * outcome); the rest sum. `score-difference` is deliberately absent — it is
 * derived at comparison time, and the audit trail keeps "what was recorded"
 * separable from "what was computed".
 */
export function footballDescriptor(
  overrides?: Partial<DisciplineDescriptor>,
): DisciplineDescriptor {
  const segmentTypes = ['half', 'extra-time'];
  return {
    descriptorId: '01890000-0000-7000-8000-00000000f001',
    alias: 'football',
    version: '1.3.0',
    name: 'Football',
    attribution: {
      author: 'CopaLibre',
      licence: 'AGPL-3.0-only',
      sourceUrl: 'https://github.com/SebaSOFT/copalibre',
    },
    participantTypes: ['team'],
    rosterConstraints: { minPlayers: 11, maxPlayers: 11, maxSubstitutes: 12 },
    segmentTypes: [
      { name: 'half', label: 'Half', timed: true, defaultDurationSeconds: 2700 },
      { name: 'extra-time', label: 'Extra time', timed: true, defaultDurationSeconds: 900 },
    ],
    eventDefinitions: [
      {
        code: 'goal',
        label: 'Goal',
        category: 'positive',
        permittedSegmentTypes: segmentTypes,
        actorRequirement: 'person',
        payloadSchema: {
          type: 'object',
          properties: {
            assistedBy: { type: 'string' },
            penalty: { type: 'boolean' },
            goalkeeperId: { type: 'string' },
          },
        },
        effects: [
          { kind: 'score', awardTo: 'actor', delta: 1 },
          { kind: 'statistic', statisticCode: 'goals-for', delta: 1 },
          {
            kind: 'statistic',
            statisticCode: 'goals-against',
            delta: 1,
            awardTo: 'every-other-side',
          },
          {
            kind: 'statistic',
            statisticCode: 'assists',
            delta: 1,
            awardTo: { payloadField: 'assistedBy' },
          },
          {
            kind: 'roster-role-snapshot',
            payloadField: 'goalkeeperId',
            role: 'goalkeeper',
            side: 'every-other-side',
          },
        ],
      },
      {
        code: 'own-goal',
        label: 'Own goal',
        category: 'negative',
        permittedSegmentTypes: segmentTypes,
        actorRequirement: 'person',
        payloadSchema: { type: 'object', properties: {} },
        effects: [
          { kind: 'score', awardTo: 'every-other-side', delta: 1 },
          {
            kind: 'statistic',
            statisticCode: 'goals-for',
            delta: 1,
            awardTo: 'every-other-side',
          },
          { kind: 'statistic', statisticCode: 'goals-against', delta: 1 },
          { kind: 'statistic', statisticCode: 'player-own-goals', delta: 1 },
        ],
      },
      {
        code: 'substitution',
        label: 'Substitution',
        category: 'neutral',
        permittedSegmentTypes: segmentTypes,
        actorRequirement: 'side',
        payloadSchema: {
          type: 'object',
          properties: { playerOutId: { type: 'string' }, playerInId: { type: 'string' } },
          required: ['playerOutId', 'playerInId'],
        },
        personPayloadFields: ['playerOutId', 'playerInId'],
      },
      {
        code: 'yellow-card',
        label: 'Yellow card',
        category: 'negative',
        permittedSegmentTypes: segmentTypes,
        actorRequirement: 'person',
        payloadSchema: { type: 'object', properties: { reason: { type: 'string' } } },
        effects: [{ kind: 'statistic', statisticCode: 'yellow-cards', delta: 1 }],
      },
      {
        code: 'red-card',
        label: 'Red card',
        category: 'negative',
        permittedSegmentTypes: segmentTypes,
        actorRequirement: 'person',
        payloadSchema: { type: 'object', properties: { reason: { type: 'string' } } },
        effects: [{ kind: 'statistic', statisticCode: 'red-cards', delta: 1 }],
      },
      ...segmentThresholdEventDefinitions(segmentTypes),
    ],
    statistics: [
      { code: 'goals-for', label: 'Goals for', aggregation: 'sum' },
      { code: 'goals-against', label: 'Goals against', aggregation: 'sum' },
      { code: 'player-own-goals', label: 'Own goals', aggregation: 'sum' },
      { code: 'assists', label: 'Assists', aggregation: 'sum' },
      { code: 'yellow-cards', label: 'Yellow cards', aggregation: 'sum' },
      { code: 'red-cards', label: 'Red cards', aggregation: 'sum' },
      { code: 'wins', label: 'Wins', aggregation: 'sum' },
      { code: 'draws', label: 'Draws', aggregation: 'sum' },
      { code: 'losses', label: 'Losses', aggregation: 'sum' },
      { code: 'points', label: 'Points', aggregation: 'sum' },
      { code: 'played', label: 'Played', aggregation: 'count' },
    ],
    collectors: [
      {
        code: 'goals-for',
        label: {
          en: 'Goals',
          es: 'Goles',
          fr: 'Buts',
          de: 'Tore',
          it: 'Gol',
          pt: 'Gols',
          ru: 'Голы',
          zh: '进球',
        },
        source: { kind: 'event', definitionCodes: ['goal'], actorSource: 'primary' },
        measure: { kind: 'count' },
        granularity: { actor: 'person', competition: 'match' },
      },
      {
        code: 'assists',
        label: {
          en: 'Assists',
          es: 'Asistencias',
          fr: 'Passes décisives',
          de: 'Vorlagen',
          it: 'Assist',
          pt: 'Assistências',
          ru: 'Передачи',
          zh: '助攻',
        },
        source: {
          kind: 'event',
          definitionCodes: ['goal'],
          actorSource: { payloadField: 'assistedBy' },
        },
        measure: { kind: 'count' },
        granularity: { actor: 'person', competition: 'match' },
      },
      {
        code: 'yellow-cards',
        label: {
          en: 'Yellow cards',
          es: 'Tarjetas amarillas',
          fr: 'Cartons jaunes',
          de: 'Gelbe Karten',
          it: 'Cartellini gialli',
          pt: 'Cartões amarelos',
          ru: 'Желтые карточки',
          zh: '黄牌',
        },
        source: { kind: 'event', definitionCodes: ['yellow-card'], actorSource: 'primary' },
        measure: { kind: 'count' },
        granularity: { actor: 'person', competition: 'match' },
      },
      {
        code: 'red-cards',
        label: {
          en: 'Red cards',
          es: 'Tarjetas rojas',
          fr: 'Cartons rouges',
          de: 'Rote Karten',
          it: 'Cartellini rossi',
          pt: 'Cartões vermelhos',
          ru: 'Красные карточки',
          zh: '红牌',
        },
        source: { kind: 'event', definitionCodes: ['red-card'], actorSource: 'primary' },
        measure: { kind: 'count' },
        granularity: { actor: 'person', competition: 'match' },
      },
      {
        code: 'career-goals',
        label: {
          en: 'Career goals',
          es: 'Goles en carrera',
          fr: 'Buts en carrière',
          de: 'Karrieretore',
          it: 'Gol in carriera',
          pt: 'Gols na carreira',
          ru: 'Голы за карьеру',
          zh: '生涯进球',
        },
        source: { kind: 'event', definitionCodes: ['goal'], actorSource: 'primary' },
        measure: { kind: 'count' },
        granularity: { actor: 'person', competition: 'organization' },
      },
    ],
    tableLayouts: [
      {
        code: 'top-scorers',
        target: 'player-ranking',
        label: {
          en: 'Top Scorers',
          es: 'Goleadores',
          fr: 'Meilleurs buteurs',
          de: 'Torschützenkönige',
          it: 'Capocannonieri',
          pt: 'Artilheiros',
          ru: 'Бомбардиры',
          zh: '最佳射手',
        },
        entityGranularity: 'person',
        defaultSort: [{ columnCode: 'goals', direction: 'desc' }],
        columns: [
          {
            code: 'rank',
            header: {
              en: 'Rank',
              es: 'Pos',
              fr: 'Rang',
              de: 'Rang',
              it: 'Pos',
              pt: 'Pos',
              ru: 'Место',
              zh: '排名',
            },
            source: { kind: 'rank' },
            format: 'number',
          },
          {
            code: 'player',
            header: {
              en: 'Player',
              es: 'Jugador',
              fr: 'Joueur',
              de: 'Spieler',
              it: 'Giocatore',
              pt: 'Jogador',
              ru: 'Игрок',
              zh: '球员',
            },
            source: { kind: 'actor-name' },
            format: 'text',
          },
          {
            code: 'team',
            header: {
              en: 'Team',
              es: 'Equipo',
              fr: 'Équipe',
              de: 'Mannschaft',
              it: 'Squadra',
              pt: 'Equipe',
              ru: 'Команда',
              zh: '球队',
            },
            source: { kind: 'team-name' },
            format: 'text',
          },
          {
            code: 'goals',
            header: {
              en: 'Goals',
              es: 'Goles',
              fr: 'Buts',
              de: 'Tore',
              it: 'Gol',
              pt: 'Gols',
              ru: 'Голы',
              zh: '进球',
            },
            source: { kind: 'collector', code: 'goals-for' },
            format: 'number',
          },
        ],
      },
      {
        code: 'assists',
        target: 'player-ranking',
        label: {
          en: 'Assists',
          es: 'Asistencias',
          fr: 'Passes décisives',
          de: 'Vorlagen',
          it: 'Assist',
          pt: 'Assistências',
          ru: 'Передачи',
          zh: '助攻',
        },
        entityGranularity: 'person',
        defaultSort: [{ columnCode: 'assists', direction: 'desc' }],
        columns: [
          {
            code: 'rank',
            header: {
              en: 'Rank',
              es: 'Pos',
              fr: 'Rang',
              de: 'Rang',
              it: 'Pos',
              pt: 'Pos',
              ru: 'Место',
              zh: '排名',
            },
            source: { kind: 'rank' },
            format: 'number',
          },
          {
            code: 'player',
            header: {
              en: 'Player',
              es: 'Jugador',
              fr: 'Joueur',
              de: 'Spieler',
              it: 'Giocatore',
              pt: 'Jogador',
              ru: 'Игрок',
              zh: '球员',
            },
            source: { kind: 'actor-name' },
            format: 'text',
          },
          {
            code: 'team',
            header: {
              en: 'Team',
              es: 'Equipo',
              fr: 'Équipe',
              de: 'Mannschaft',
              it: 'Squadra',
              pt: 'Equipe',
              ru: 'Команда',
              zh: '球队',
            },
            source: { kind: 'team-name' },
            format: 'text',
          },
          {
            code: 'assists',
            header: {
              en: 'Assists',
              es: 'Asistencias',
              fr: 'Passes décisives',
              de: 'Vorlagen',
              it: 'Assist',
              pt: 'Assistências',
              ru: 'Передачи',
              zh: '助攻',
            },
            source: { kind: 'collector', code: 'assists' },
            format: 'number',
          },
        ],
      },
      {
        code: 'cards',
        target: 'player-ranking',
        label: {
          en: 'Cards',
          es: 'Tarjetas',
          fr: 'Cartons',
          de: 'Karten',
          it: 'Cartellini',
          pt: 'Cartões',
          ru: 'Карточки',
          zh: '红黄牌',
        },
        entityGranularity: 'person',
        defaultSort: [
          { columnCode: 'red-cards', direction: 'desc' },
          { columnCode: 'yellow-cards', direction: 'desc' },
        ],
        columns: [
          {
            code: 'rank',
            header: {
              en: 'Rank',
              es: 'Pos',
              fr: 'Rang',
              de: 'Rang',
              it: 'Pos',
              pt: 'Pos',
              ru: 'Место',
              zh: '排名',
            },
            source: { kind: 'rank' },
            format: 'number',
          },
          {
            code: 'player',
            header: {
              en: 'Player',
              es: 'Jugador',
              fr: 'Joueur',
              de: 'Spieler',
              it: 'Giocatore',
              pt: 'Jogador',
              ru: 'Игрок',
              zh: '球员',
            },
            source: { kind: 'actor-name' },
            format: 'text',
          },
          {
            code: 'team',
            header: {
              en: 'Team',
              es: 'Equipo',
              fr: 'Équipe',
              de: 'Mannschaft',
              it: 'Squadra',
              pt: 'Equipe',
              ru: 'Команда',
              zh: '球队',
            },
            source: { kind: 'team-name' },
            format: 'text',
          },
          {
            code: 'red-cards',
            header: {
              en: 'Red cards',
              es: 'Tarjetas rojas',
              fr: 'Cartons rouges',
              de: 'Rote Karten',
              it: 'Cartellini rossi',
              pt: 'Cartões vermelhos',
              ru: 'Красные карточки',
              zh: '红牌',
            },
            shortHeader: {
              en: 'RC',
              es: 'TR',
              fr: 'CR',
              de: 'RK',
              it: 'CR',
              pt: 'CV',
              ru: 'КК',
              zh: '红牌',
            },
            source: { kind: 'collector', code: 'red-cards' },
            format: 'number',
          },
          {
            code: 'yellow-cards',
            header: {
              en: 'Yellow cards',
              es: 'Tarjetas amarillas',
              fr: 'Cartons jaunes',
              de: 'Gelbe Karten',
              it: 'Cartellini gialli',
              pt: 'Cartões amarelos',
              ru: 'Желтые карточки',
              zh: '黄牌',
            },
            shortHeader: {
              en: 'YC',
              es: 'TA',
              fr: 'CJ',
              de: 'GK',
              it: 'CG',
              pt: 'CA',
              ru: 'ЖК',
              zh: '黄牌',
            },
            source: { kind: 'collector', code: 'yellow-cards' },
            format: 'number',
          },
        ],
      },
    ],
    rosterRoles: [
      { code: 'goalkeeper', label: 'Goalkeeper', badge: 'GK' },
      { code: 'captain', label: 'Captain', badge: 'C' },
    ],
    scoringInputs: [{ code: 'goals', label: 'Goals', source: 'event-derived' }],
    availableFormats: [
      'league',
      'round-robin',
      'round-robin-home-away',
      'round-robin-single-leg',
      'single-elimination',
      'double-elimination',
    ],
    notificationRuleCapabilities: ['threshold-count'],
    // No target: whoever leads on goals at full time takes the match, and level
    // sides draw. Cup ties override this where the field policy permits.
    winCondition: winConditionScript('football-win-condition', { unit: 'goals' }),
    defaults: {
      format: 'round-robin',
      registration: {
        publicOpen: false,
        requiresCheckIn: false,
        region: null,
        capacity: null,
      },
      scoring: { pointsPerWin: 3, pointsPerDraw: 1, pointsPerLoss: 0 },
      tiebreakers: ['points', 'score-difference', 'goals-for'],
      segments: { regulationCount: 2, overtimeEnabled: false },
      venuePolicy: { neutralGround: false },
    },
    fieldPolicies: {
      format: { permission: { kind: 'replaced' }, mutationClass: 'blocked_after_results' },
      'registration.region': { permission: { kind: 'replaced' }, mutationClass: 'safe' },
      'registration.capacity': {
        permission: { kind: 'replaced' },
        mutationClass: 'requires_rebuild',
      },
      'registration.publicOpen': { permission: { kind: 'replaced' }, mutationClass: 'safe' },
      'registration.requiresCheckIn': {
        permission: { kind: 'replaced' },
        mutationClass: 'requires_rebuild',
      },
      'registration.checkInClosesAt': {
        permission: { kind: 'replaced' },
        mutationClass: 'requires_rebuild',
      },
      'scoring.pointsPerWin': {
        permission: { kind: 'replaced' },
        mutationClass: 'blocked_after_results',
      },
      'scoring.pointsPerDraw': {
        permission: { kind: 'replaced' },
        mutationClass: 'blocked_after_results',
      },
      tiebreakers: {
        permission: { kind: 'merged', strategy: 'union-list' },
        mutationClass: 'requires_rebuild',
      },
      segments: {
        permission: { kind: 'merged', strategy: 'shallow-object' },
        mutationClass: 'requires_rebuild',
      },
      'venuePolicy.neutralGround': { permission: { kind: 'inherited' }, mutationClass: 'safe' },
      // A cup tie cannot end level, so replacing the win condition is permitted.
      winCondition: { permission: { kind: 'replaced' }, mutationClass: 'requires_rebuild' },
      tableLayouts: { permission: { kind: 'replaced' }, mutationClass: 'safe' },
    },
    ...overrides,
  };
}
