import type { SupportedLanguage } from '@copalibre/domain';

/**
 * The launcher's own words, one set per supported language. The page renders the set for the
 * language in the address, and the script re-renders from the same set when the viewer picks another,
 * so a change of language never needs a reload.
 */
export const TV_LAUNCHER_LABELS: Readonly<
  Record<SupportedLanguage, Readonly<Record<string, string>>>
> = {
  en: {
    title: 'TV display launcher',
    intro: 'Configure a venue screen or broadcast overlay.',
    organization: 'Organization',
    tournament: 'Tournament',
    view: 'View',
    dashboard: 'Rotating dashboard',
    standings: 'Standings',
    pinnedMatch: 'Pinned match',
    overlay: 'Broadcast overlay',
    stage: 'Stage',
    match: 'Match',
    background: 'Background',
    discipline: 'Discipline',
    neutral: 'Neutral',
    chroma: 'Chroma green',
    football: 'Football pitch',
    court: 'Indoor court',
    language: 'Language',
    launch: 'Launch TV display',
    unavailable: 'No published tournaments are available for this organization.',
    loadError: 'Tournament data is temporarily unavailable.',
    noMatches: 'No matches are available to pin for this tournament.',
    publicSite: 'Public site',
    emptyOrganizations: 'No organizations are available.',
    matchList: 'Match list',
    courtGroup: 'Follow the live match of a court',
    round: 'Round',
  },
  es: {
    title: 'Lanzador de pantalla TV',
    intro: 'Configura una pantalla del recinto o una superposición de transmisión.',
    organization: 'Organización',
    tournament: 'Torneo',
    view: 'Vista',
    dashboard: 'Panel rotativo',
    standings: 'Tabla de posiciones',
    pinnedMatch: 'Partido fijado',
    overlay: 'Superposición de transmisión',
    stage: 'Etapa',
    match: 'Partido',
    background: 'Fondo',
    discipline: 'Disciplina',
    neutral: 'Neutro',
    chroma: 'Verde chroma',
    football: 'Cancha de fútbol',
    court: 'Cancha cubierta',
    language: 'Idioma',
    launch: 'Lanzar pantalla TV',
    unavailable: 'No hay torneos publicados disponibles para esta organización.',
    loadError: 'Los datos del torneo no están disponibles temporalmente.',
    noMatches: 'No hay partidos disponibles para fijar en este torneo.',
    publicSite: 'Sitio público',
    emptyOrganizations: 'No hay organizaciones disponibles.',
    matchList: 'Lista de partidos',
    courtGroup: 'Seguir el partido en vivo de una cancha',
    round: 'Ronda',
  },
  fr: {
    title: 'Lanceur d’écran TV',
    intro: 'Configurez un écran de salle ou une incrustation de diffusion.',
    organization: 'Organisation',
    tournament: 'Tournoi',
    view: 'Vue',
    dashboard: 'Tableau tournant',
    standings: 'Classement',
    pinnedMatch: 'Match épinglé',
    overlay: 'Incrustation de diffusion',
    stage: 'Étape',
    match: 'Match',
    background: 'Arrière-plan',
    discipline: 'Discipline',
    neutral: 'Neutre',
    chroma: 'Vert chroma',
    football: 'Terrain de football',
    court: 'Terrain couvert',
    language: 'Langue',
    launch: 'Lancer l’écran TV',
    unavailable: 'Aucun tournoi publié pour cette organisation.',
    loadError: 'Données du tournoi temporairement indisponibles.',
    noMatches: 'Aucun match à épingler pour ce tournoi.',
    publicSite: 'Site public',
    emptyOrganizations: 'Aucune organisation disponible.',
    matchList: 'Liste des matchs',
    courtGroup: 'Suivre le match en direct d’un terrain',
    round: 'Ronde',
  },
  pt: {
    title: 'Lançador de tela TV',
    intro: 'Configure uma tela do local ou uma sobreposição de transmissão.',
    organization: 'Organização',
    tournament: 'Torneio',
    view: 'Visualização',
    dashboard: 'Painel rotativo',
    standings: 'Classificação',
    pinnedMatch: 'Partida fixada',
    overlay: 'Sobreposição de transmissão',
    stage: 'Etapa',
    match: 'Partida',
    background: 'Plano de fundo',
    discipline: 'Modalidade',
    neutral: 'Neutro',
    chroma: 'Verde chroma',
    football: 'Campo de futebol',
    court: 'Quadra coberta',
    language: 'Idioma',
    launch: 'Iniciar tela TV',
    unavailable: 'Não há torneios publicados disponíveis para esta organização.',
    loadError: 'Dados do torneio indisponíveis temporariamente.',
    noMatches: 'Não há partidas disponíveis para fixar neste torneio.',
    publicSite: 'Site público',
    emptyOrganizations: 'Nenhuma organização disponível.',
    matchList: 'Lista de jogos',
    courtGroup: 'Seguir o jogo ao vivo de uma quadra',
    round: 'Rodada',
  },
  it: {
    title: 'Avvio schermo TV',
    intro: 'Configura uno schermo per la sede o una sovrapposizione broadcast.',
    organization: 'Organizzazione',
    tournament: 'Torneo',
    view: 'Vista',
    dashboard: 'Pannello a rotazione',
    standings: 'Classifica',
    pinnedMatch: 'Partita fissata',
    overlay: 'Sovrapposizione broadcast',
    stage: 'Fase',
    match: 'Partita',
    background: 'Sfondo',
    discipline: 'Disciplina',
    neutral: 'Neutro',
    chroma: 'Verde chroma',
    football: 'Campo da calcio',
    court: 'Campo indoor',
    language: 'Lingua',
    launch: 'Avvia schermo TV',
    unavailable: 'Nessun torneo pubblicato disponibile per questa organizzazione.',
    loadError: 'Dati del torneo temporaneamente non disponibili.',
    noMatches: 'Non ci sono partite da fissare per questo torneo.',
    publicSite: 'Sito pubblico',
    emptyOrganizations: 'Nessuna organizzazione disponibile.',
    matchList: 'Elenco delle partite',
    courtGroup: 'Seguire la partita in diretta di un campo',
    round: 'Turno',
  },
  de: {
    title: 'TV-Bildschirm starten',
    intro: 'Richten Sie einen Hallenbildschirm oder eine Broadcast-Einblendung ein.',
    organization: 'Organisation',
    tournament: 'Turnier',
    view: 'Ansicht',
    dashboard: 'Rotierendes Dashboard',
    standings: 'Tabelle',
    pinnedMatch: 'Fixiertes Spiel',
    overlay: 'Broadcast-Einblendung',
    stage: 'Phase',
    match: 'Spiel',
    background: 'Hintergrund',
    discipline: 'Disziplin',
    neutral: 'Neutral',
    chroma: 'Chroma-Grün',
    football: 'Fußballfeld',
    court: 'Hallenfeld',
    language: 'Sprache',
    launch: 'TV-Bildschirm starten',
    unavailable: 'Für diese Organisation sind keine veröffentlichten Turniere verfügbar.',
    loadError: 'Turnierdaten sind vorübergehend nicht verfügbar.',
    noMatches: 'Für dieses Turnier gibt es keine fixierbaren Spiele.',
    publicSite: 'Öffentliche Website',
    emptyOrganizations: 'Keine Organisationen verfügbar.',
    matchList: 'Spielliste',
    courtGroup: 'Dem Live-Spiel eines Platzes folgen',
    round: 'Runde',
  },
  ru: {
    title: 'Запуск ТВ-экрана',
    intro: 'Настройте экран площадки или эфирную накладку.',
    organization: 'Организация',
    tournament: 'Турнир',
    view: 'Вид',
    dashboard: 'Сменяемая панель',
    standings: 'Таблица',
    pinnedMatch: 'Закреплённый матч',
    overlay: 'Эфирная накладка',
    stage: 'Этап',
    match: 'Матч',
    background: 'Фон',
    discipline: 'Дисциплина',
    neutral: 'Нейтральный',
    chroma: 'Зелёный хромакей',
    football: 'Футбольное поле',
    court: 'Зал',
    language: 'Язык',
    launch: 'Запустить ТВ-экран',
    unavailable: 'Для этой организации нет опубликованных турниров.',
    loadError: 'Данные турнира временно недоступны.',
    noMatches: 'В этом турнире нет матчей для закрепления.',
    publicSite: 'Публичный сайт',
    emptyOrganizations: 'Организации недоступны.',
    matchList: 'Список матчей',
    courtGroup: 'Следить за матчем в эфире на площадке',
    round: 'Раунд',
  },
  zh: {
    title: '电视屏幕启动器',
    intro: '配置场馆屏幕或直播叠加层。',
    organization: '组织',
    tournament: '赛事',
    view: '视图',
    dashboard: '轮播面板',
    standings: '排名',
    pinnedMatch: '固定比赛',
    overlay: '直播叠加层',
    stage: '阶段',
    match: '比赛',
    background: '背景',
    discipline: '项目',
    neutral: '中性',
    chroma: '色键绿',
    football: '足球场',
    court: '室内球场',
    language: '语言',
    launch: '启动电视屏幕',
    unavailable: '此组织没有已发布的赛事。',
    loadError: '赛事数据暂时不可用。',
    noMatches: '此赛事没有可固定的比赛。',
    publicSite: '公开网站',
    emptyOrganizations: '没有可用组织。',
    matchList: '比赛列表',
    courtGroup: '跟随某个场地的直播比赛',
    round: '轮次',
  },
};
